# -*- coding: utf-8 -*-
"""a1_lstm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/truongminh3105/a1-lstm.c0c1f883-b98a-4a32-acc9-1282e70ece41.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T132228Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D53587a30a16cef78687926b5b17a697a9432a3647a726999f5d772222af327610203baf84fb3edc37fb2e7f5a709154a4f095838f3feaa688caec1b1ee46d9e010036b3600f3ca162c1b18d5277dfa1785379f8b03a2073108e53736268a0b26535ac61406ba9dd01dca56094740dc037e68bb671e2ba1c49832f94e8a11aba0eca1acddc71f5415185675596383797d3f3bbb971e840f1978684ed5a2d3859bb49f8b57942d96e81e7596bfb9a922a88f5b94fa6f60509f972272abfa73fe548555a2d90371c563ee132b4ead41766d185625a597948a59bcfbe9966c4744a1e5999ca163f73f05f0edc2312f9fbb25a4294266bef4dd921f4f7b6d744b59f6
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

truongminh3105_vqa_vnf_dataset_path = kagglehub.dataset_download('truongminh3105/vqa-vnf-dataset')
truongminh3105_my_vqa_weights_path = kagglehub.dataset_download('truongminh3105/my-vqa-weights')

print('Data source import complete.')

from huggingface_hub import login


!pip install gradio torch torchvision transformers peft accelerate bitsandbytes sentencepiece protobuf timm nltk rouge-score bert-score pandas tabulate
!pip install -r /kaggle/input/datasets/truongminh3105/vqa-vnf-dataset/requirements.txt
!pip install -U bitsandbytes

import os
import re
import copy
from collections import Counter
import pandas as pd
import json
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.auto import tqdm
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import torchvision.transforms as transforms
import torchvision.models as models


BASE_DIR = '/kaggle/input/datasets/truongminh3105/vqa-vnf-dataset/dataset'
IMG_DIR = BASE_DIR
ANNOTATIONS_DIR = os.path.join(BASE_DIR, 'annotations')

TRAIN_JSON_PATH = os.path.join(ANNOTATIONS_DIR, 'train_augmented.json')
VAL_JSON_PATH = os.path.join(ANNOTATIONS_DIR, 'val.json')
TEST_JSON_PATH = os.path.join(ANNOTATIONS_DIR, 'test.json')

WORKING_DIR = '/kaggle/working'
WEIGHTS_DIR = os.path.join(WORKING_DIR, 'weights')
os.makedirs(WEIGHTS_DIR, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Đang sử dụng thiết bị: {device}")

class Vocabulary:
    def __init__(self, freq_threshold=2):
        self.freq_threshold = freq_threshold
        self.itos = {0: "<PAD>", 1: "<SOS>", 2: "<EOS>", 3: "<UNK>"}
        self.stoi = {"<PAD>": 0, "<SOS>": 1, "<EOS>": 2, "<UNK>": 3}
        self.idx = 4

    def __len__(self):
        return len(self.itos)

    @staticmethod
    def tokenizer(text):
        text = str(text).lower()
        text = re.sub(r'[^\w\s]', '', text)
        return text.split()

    def build_vocabulary(self, sentence_list):
        frequencies = Counter()
        for sentence in sentence_list:
            for word in self.tokenizer(sentence):
                frequencies[word] += 1

        for word, count in frequencies.items():
            if count >= self.freq_threshold:
                self.stoi[word] = self.idx
                self.itos[self.idx] = word
                self.idx += 1

    def numericalize(self, text):
        tokenized_text = self.tokenizer(text)
        return [
            self.stoi[token] if token in self.stoi else self.stoi["<UNK>"]
            for token in tokenized_text
        ]

def load_vqa_json(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    flattened_data = []
    for item in data:
        img_path = item['image_path']
        for qa in item['qa_pairs']:
            flattened_data.append({
                'image_path': img_path,
                'question': qa['question'],
                'answer': qa['answer'],
                'type': qa['type'] 
            })
    return pd.DataFrame(flattened_data)

print("Đang đọc dữ liệu JSON và xây dựng Vocabulary...")
train_df = load_vqa_json(TRAIN_JSON_PATH)
val_df = load_vqa_json(VAL_JSON_PATH)
all_text = train_df['question'].tolist() + train_df['answer'].tolist() + \
           val_df['question'].tolist() + val_df['answer'].tolist()

vocab = Vocabulary(freq_threshold=2)
vocab.build_vocabulary(all_text)

print(f"Kích thước từ vựng: {len(vocab)} từ.")

import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import torch
from torch.nn.utils.rnn import pad_sequence
import os
from PIL import Image
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def collate_fn_phobert(batch):
    images, input_ids, attention_masks, answers = zip(*batch)
    images = torch.stack(images, 0)
    input_ids = torch.stack(input_ids, 0)
    attention_masks = torch.stack(attention_masks, 0)
    answers_padded = pad_sequence(answers, batch_first=True, padding_value=0)
    return images, input_ids, attention_masks, answers_padded

train_transform = transforms.Compose([
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

class VQA_ViT_PhoBERT_Dataset(Dataset):
    def __init__(self, df, img_dir, tokenizer, vocab, transform=None, max_len=50):
        self.df = df
        self.img_dir = img_dir
        self.tokenizer = tokenizer
        self.vocab = vocab
        self.transform = transform
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        img_path = os.path.join(self.img_dir, row['image_path'])

        try:
            image = Image.open(img_path).convert('RGB')
        except Exception:
            image = Image.new('RGB', (224, 224), (0, 0, 0))

        if self.transform:
            image = self.transform(image)

        question = row['question']
        encoded_q = self.tokenizer(
            question,
            truncation=True,
            max_length=self.max_len,
            padding='max_length',
            return_tensors='pt'
        )

        input_ids = encoded_q['input_ids'].squeeze(0)
        attention_mask = encoded_q['attention_mask'].squeeze(0)

        answer = row['answer']
        ans_tokens = [self.vocab.stoi["<SOS>"]] + self.vocab.numericalize(answer) + [self.vocab.stoi["<EOS>"]]
        answer_tensor = torch.tensor(ans_tokens)

        return image, input_ids, attention_mask, answer_tensor

train_dataset = VQA_ViT_PhoBERT_Dataset(train_df, IMG_DIR, tokenizer, vocab, transform=train_transform)
val_dataset = VQA_ViT_PhoBERT_Dataset(val_df, IMG_DIR, tokenizer, vocab, transform=val_transform)

BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn_phobert, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn_phobert, num_workers=4)

print(f"Tổng mẫu Train (ViT+PhoBERT): {len(train_dataset)}")
print(f"Tổng mẫu Val (ViT+PhoBERT): {len(val_dataset)}")

import torch
import torch.nn as nn
import torchvision.models as models
import torch.nn.functional as F
from transformers import AutoModel

class SpatialAttention(nn.Module):
    def __init__(self, encoder_dim, decoder_dim, attention_dim):
        super(SpatialAttention, self).__init__()
        self.encoder_att = nn.Linear(encoder_dim, attention_dim)
        self.decoder_att = nn.Linear(decoder_dim, attention_dim)
        self.full_att = nn.Linear(attention_dim, 1)

    def forward(self, encoder_out, decoder_hidden):
        att1 = self.encoder_att(encoder_out)
        att2 = self.decoder_att(decoder_hidden)
        combined = torch.tanh(att1 + att2.unsqueeze(1))
        attention = self.full_att(combined).squeeze(2)
        alpha = F.softmax(attention, dim=1)
        context = (encoder_out * alpha.unsqueeze(2)).sum(dim=1)
        return context, alpha

class VQA_A1_ViT_PhoBERT_Model(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size, num_layers=2, dropout_rate=0.4):
        super(VQA_A1_ViT_PhoBERT_Model, self).__init__()

        self.vit = AutoModel.from_pretrained("google/vit-base-patch16-224-in21k")
        self.img_dim = 768

        self.phobert = AutoModel.from_pretrained("vinai/phobert-base")
        self.text_dim = 768

        self.embedding = nn.Embedding(vocab_size, embed_size, padding_idx=0)
        self.attention = SpatialAttention(self.img_dim, hidden_size, attention_dim=512)

        self.text_fc = nn.Linear(self.text_dim, hidden_size)
        self.fusion_fc = nn.Linear(self.img_dim + hidden_size, hidden_size)

        self.decoder_cell = nn.ModuleList()
        self.decoder_cell.append(nn.LSTMCell(embed_size + self.img_dim, hidden_size))
        for _ in range(1, num_layers):
            self.decoder_cell.append(nn.LSTMCell(hidden_size, hidden_size))

        self.vocab_classifier = nn.Linear(hidden_size, vocab_size)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, images, input_ids, attention_mask, answers=None):
        batch_size = images.size(0)

        with torch.no_grad():
            vit_outputs = self.vit(pixel_values=images)
            features = vit_outputs.last_hidden_state[:, 1:, :]

        with torch.no_grad():
            phobert_outputs = self.phobert(input_ids=input_ids, attention_mask=attention_mask)
            text_features = phobert_outputs.pooler_output

        text_features = self.text_fc(text_features)
        avg_img = features.mean(dim=1)
        combined_init = torch.cat([avg_img, text_features], dim=1)

        h_d = [self.dropout(self.fusion_fc(combined_init)) for _ in range(len(self.decoder_cell))]
        c_d = [torch.zeros_like(h_d[0]) for _ in range(len(self.decoder_cell))]

        if answers is not None:
            ans_embeds = self.embedding(answers)
            seq_len = answers.size(1) - 1
            logits_list = []

            for t in range(seq_len):
                context, _ = self.attention(features, h_d[0])
                step_input = torch.cat([ans_embeds[:, t, :], context], dim=1)

                new_h, new_c = [], []
                curr_input = step_input

                for i, cell in enumerate(self.decoder_cell):
                    h_i, c_i = cell(curr_input, (h_d[i], c_d[i]))
                    new_h.append(h_i)
                    new_c.append(c_i)
                    curr_input = h_i

                h_d, c_d = new_h, new_c
                logits = self.vocab_classifier(self.dropout(h_d[-1]))
                logits_list.append(logits)

            return torch.stack(logits_list, dim=1)
        else:
            return h_d, c_d, features

EMBED_SIZE = 512
HIDDEN_SIZE = 1024
NUM_LAYERS = 2

model = VQA_A1_ViT_PhoBERT_Model(
    vocab_size=len(vocab),
    embed_size=EMBED_SIZE,
    hidden_size=HIDDEN_SIZE,
    num_layers=NUM_LAYERS,
    dropout_rate=0.4
).to(device)
if torch.cuda.device_count() > 1:
    print(f"🔥 Đang sử dụng {torch.cuda.device_count()} GPUs với DataParallel!")
    model = nn.DataParallel(model)
else:
    print("Đang sử dụng 1 GPU (hoặc CPU).")
print("Đã khởi tạo Mô hình A1.")

import copy
import torch.optim as optim
import os
import torch.nn.functional as F
from tqdm.auto import tqdm
from transformers import get_cosine_schedule_with_warmup
import torch.cuda.amp as amp

def label_smoothed_nll_loss(logits, targets, epsilon=0.1, ignore_index=0):
    log_probs = F.log_softmax(logits, dim=-1)
    nll_loss = F.nll_loss(log_probs, targets, ignore_index=ignore_index, reduction='sum')
    vocab_size = log_probs.size(-1)
    smooth_loss = -log_probs.sum(dim=-1).sum()
    num_valid_tokens = (targets != ignore_index).sum().item()
    if num_valid_tokens == 0: return nll_loss * 0.0
    loss = (1.0 - epsilon) * nll_loss + (epsilon / vocab_size) * smooth_loss
    return loss / num_valid_tokens

EPOCHS = 5
best_val_loss = float('inf')
MODEL_SAVE_PATH = os.path.join(WEIGHTS_DIR, 'vqa_model_A1_vit_phobert.pth')

optimizer = optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-4)

total_steps = len(train_loader) * EPOCHS
warmup_steps = int(0.1 * total_steps)

scheduler = get_cosine_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps
)

history_train_loss = []
history_val_loss = []
scaler = torch.amp.GradScaler('cuda')
base_model = model.module if hasattr(model, 'module') else model

print("❄️ Đang đóng băng (Freeze) ViT và PhoBERT cho các epoch đầu...")
for param in base_model.vit.parameters():
    param.requires_grad = False
for param in base_model.phobert.parameters():
    param.requires_grad = False

for epoch in range(EPOCHS):
    print(f"\nEpoch {epoch+1}/{EPOCHS}")
    print("-" * 15)

    if epoch == 2:
        print("🔥 Mở băng (Unfreeze) ViT và PhoBERT! Bắt đầu Fine-tune toàn bộ.")
        for param in base_model.vit.parameters():
            param.requires_grad = True
        for param in base_model.phobert.parameters():
            param.requires_grad = True

    model.train()
    train_loss = 0.0

    for images, input_ids, attention_mask, answers in tqdm(train_loader, desc="Training"):
        images = images.to(device)
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        answers = answers.to(device)

        optimizer.zero_grad()
        with torch.amp.autocast('cuda'):
            outputs = model(images, input_ids, attention_mask, answers)
            outputs = outputs.reshape(-1, outputs.shape[2])
            targets = answers[:, 1:].reshape(-1)
            loss = label_smoothed_nll_loss(outputs, targets, epsilon=0.1, ignore_index=vocab.stoi["<PAD>"])

        scaler.scale(loss).backward()

        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        scaler.step(optimizer)
        scaler.update()

        scheduler.step()
        train_loss += loss.item() * images.size(0)

    epoch_train_loss = train_loss / len(train_dataset)
    history_train_loss.append(epoch_train_loss)

    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for images, input_ids, attention_mask, answers in tqdm(val_loader, desc="Validation"):
            images = images.to(device)
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)
            answers = answers.to(device)

            with torch.amp.autocast('cuda'):
                outputs = model(images, input_ids, attention_mask, answers)
                outputs = outputs.reshape(-1, outputs.shape[2])
                targets = answers[:, 1:].reshape(-1)
                loss = label_smoothed_nll_loss(outputs, targets, epsilon=0.1, ignore_index=vocab.stoi["<PAD>"])

            val_loss += loss.item() * images.size(0)

    epoch_val_loss = val_loss / len(val_dataset)
    history_val_loss.append(epoch_val_loss)

    current_lr = scheduler.get_last_lr()[0]
    print(f"Train Loss: {epoch_train_loss:.4f} | Val Loss: {epoch_val_loss:.4f} | LR: {current_lr:.6f}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss

        base_model_to_save = model.module if hasattr(model, 'module') else model
        torch.save(base_model_to_save.state_dict(), MODEL_SAVE_PATH)
        print(f"💾 Đã lưu trọng số mới tốt nhất!")

print("\n🚀 HOÀN TẤT HUẤN LUYỆN!")


import matplotlib.pyplot as plt
import os

plt.figure(figsize=(10, 6))

epochs_run = len(history_train_loss)

plt.plot(range(1, epochs_run + 1), history_train_loss, label='Training Loss', color='teal', marker='o')
plt.plot(range(1, epochs_run + 1), history_val_loss, label='Validation Loss', color='darkorange', marker='s')

plt.title('Biểu đồ Loss huấn luyện VQA (Mô hình A1: ViT + PhoBERT)', fontsize=14, pad=15)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Label Smoothed NLL Loss', fontsize=12)
plt.xticks(range(1, epochs_run + 1))
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)

PLOT_SAVE_PATH = os.path.join(WEIGHTS_DIR, 'loss_plot_A1_vit_phobert.png')
plt.savefig(PLOT_SAVE_PATH, dpi=300, bbox_inches='tight')
print(f"Đã lưu biểu đồ vào: {PLOT_SAVE_PATH}")

plt.show()

import os
import torch
from PIL import Image
import matplotlib.pyplot as plt
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def predict_a1_vit_phobert(image_path, question_text, model, vocab, device, max_len=15):
    base_model = model.module if hasattr(model, 'module') else model

    if os.path.exists(MODEL_SAVE_PATH):
        base_model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=device))
        base_model.eval()
    else:
        print(f"Lỗi: Không tìm thấy file tại {MODEL_SAVE_PATH}")
        return

    image = Image.open(image_path).convert("RGB")
    img_tensor = val_transform(image).unsqueeze(0).to(device)

    encoded_q = tokenizer(question_text, return_tensors='pt', truncation=True, max_length=50)
    input_ids = encoded_q['input_ids'].to(device)
    attention_mask = encoded_q['attention_mask'].to(device)

    predicted_words = []
    alphas = []

    with torch.no_grad():
        h_d, c_d, features = base_model(img_tensor, input_ids, attention_mask)
        current_word_idx = torch.tensor([vocab.stoi["<SOS>"]]).to(device)

        for t in range(max_len):
            context, alpha = base_model.attention(features, h_d[0])
            alphas.append(alpha.cpu().numpy())

            word_embed = base_model.embedding(current_word_idx)
            step_input = torch.cat([word_embed, context], dim=1)

            new_h, new_c = [], []
            curr_input = step_input
            for i, cell in enumerate(base_model.decoder_cell):
                h_i, c_i = cell(curr_input, (h_d[i], c_d[i]))
                new_h.append(h_i)
                new_c.append(c_i)
                curr_input = h_i

            h_d, c_d = new_h, new_c

            logits = base_model.vocab_classifier(base_model.dropout(h_d[-1]))
            _, next_word_idx = torch.max(logits, dim=1)
            word = vocab.itos[next_word_idx.item()]

            if word == "<EOS>":
                break

            predicted_words.append(word)
            current_word_idx = next_word_idx

    plt.figure(figsize=(6, 6))
    plt.imshow(image)
    plt.title(f"Q: {question_text}")
    plt.axis('off')
    plt.show()

    print(f"AI Trả lời: {' '.join(predicted_words)}")
    return predicted_words, alphas

# Test lại suy luận
test_row = val_df.sample(1).iloc[0]
test_img_path = os.path.join(IMG_DIR, test_row['image_path'])

pred, _ = predict_a1_vit_phobert(test_img_path, test_row['question'], model, vocab, device)
print(f"Đáp án đúng: {test_row['answer']}")


import os
import io
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from PIL import Image
from transformers import AutoTokenizer

# ── 1. KHỞI TẠO LẠI MÔ HÌNH VÀ TẢI TRỌNG SỐ ──────────────────────────────
print("⏳ Đang khởi tạo mô hình và tải trọng số đã lưu...")

EMBED_SIZE  = 512
HIDDEN_SIZE = 1024
NUM_LAYERS  = 2

inference_model = VQA_A1_ViT_PhoBERT_Model(
    vocab_size   = len(vocab),
    embed_size   = EMBED_SIZE,
    hidden_size  = HIDDEN_SIZE,
    num_layers   = NUM_LAYERS,
    dropout_rate = 0.0
).to(device)

MODEL_SAVE_PATH = os.path.join(WEIGHTS_DIR, 'vqa_model_A1_vit_phobert.pth')

if not os.path.exists(MODEL_SAVE_PATH):
    raise FileNotFoundError(
        f"Không tìm thấy file trọng số tại:\n  {MODEL_SAVE_PATH}\n"
        "Hãy kiểm tra lại đường dẫn WEIGHTS_DIR."
    )

inference_model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=device))
inference_model.eval()
print(f"✅ Đã tải trọng số từ: {MODEL_SAVE_PATH}\n")

# ── 2. TOKENIZER ─────────────────────────────────────────────────────────────
infer_tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

# ── 3. THAM SỐ INFERENCE ─────────────────────────────────────────────────────
NUM_GROUPS      = 3     # Số nhóm beam (diversity groups)
BEAMS_PER_GROUP = 2     # Số beam trong mỗi nhóm → tổng beam = NUM_GROUPS * BEAMS_PER_GROUP
MAX_LEN         = 15    # Số từ tối đa cho câu trả lời
LENGTH_ALPHA    = 0.7   # Length penalty: 0.0 = tắt, 0.6~0.9 = câu dài hơn
DIVERSITY_GAMMA = 0.5   # Penalty đa dạng giữa các nhóm: tăng → các nhóm khác nhau hơn

# ── 4. HÀM DECODER MỘT BƯỚC ─────────────────────────────────────────────────
def decoder_step(current_word_idx, h_d, c_d, features):
    """Chạy một bước decoder, trả về log_probs và hidden state mới."""
    with torch.no_grad():
        context, _  = inference_model.attention(features, h_d[0])
        word_embed  = inference_model.embedding(current_word_idx)
        step_input  = torch.cat([word_embed, context], dim=1)

        new_h, new_c = [], []
        curr_input = step_input
        for i, cell in enumerate(inference_model.decoder_cell):
            h_i, c_i = cell(curr_input, (h_d[i], c_d[i]))
            new_h.append(h_i)
            new_c.append(c_i)
            curr_input = h_i

        logits   = inference_model.vocab_classifier(new_h[-1])
        log_prob = F.log_softmax(logits, dim=1)

    return log_prob, new_h, new_c

def length_penalized_score(score, length, alpha=LENGTH_ALPHA):
    return score / (length ** alpha) if length > 0 else score

# ── 5. HÀM INFERENCE (DIVERSE BEAM SEARCH) ───────────────────────────────────
def infer_diverse_beam(image_pil, question_text,
                       max_len=MAX_LEN,
                       num_groups=NUM_GROUPS,
                       beams_per_group=BEAMS_PER_GROUP,
                       diversity_gamma=DIVERSITY_GAMMA):

    img_tensor = val_transform(image_pil).unsqueeze(0).to(device)

    encoded_q = infer_tokenizer(
        question_text,
        return_tensors='pt',
        truncation=True,
        max_length=50,
        padding='max_length'
    )
    input_ids      = encoded_q['input_ids'].to(device)
    attention_mask = encoded_q['attention_mask'].to(device)

    with torch.no_grad():
        h_d_init, c_d_init, features = inference_model(img_tensor, input_ids, attention_mask)

    groups = [
        [(0.0, [], h_d_init, c_d_init)]
        for _ in range(num_groups)
    ]
    completed = []   

    for _ in range(max_len):
        tokens_chosen_this_step = []

        for g in range(num_groups):
            candidates = []

            for score, words, h_d, c_d in groups[g]:
                last_token = vocab.stoi["<SOS>"] if not words                              else vocab.stoi.get(words[-1], vocab.stoi["<UNK>"])
                current_word_idx = torch.tensor([last_token]).to(device)

                log_prob, new_h, new_c = decoder_step(
                    current_word_idx, h_d, c_d, features
                )

                penalized_log_prob = log_prob[0].clone()
                for prev_token_idx in tokens_chosen_this_step:
                    penalized_log_prob[prev_token_idx] -= diversity_gamma

                topk_scores, topk_idxs = penalized_log_prob.topk(beams_per_group)
                for lp, idx in zip(topk_scores, topk_idxs):
                    word      = vocab.itos[idx.item()]
                    new_score = score + log_prob[0][idx].item() 
                    if word == "<EOS>":
                        completed.append((new_score, words))
                    else:
                        candidates.append((new_score, words + [word], new_h, new_c))
                        tokens_chosen_this_step.append(idx.item())

            if not candidates:
                groups[g] = []
                continue

            candidates.sort(
                key=lambda x: length_penalized_score(x[0], len(x[1])),
                reverse=True
            )
            groups[g] = candidates[:beams_per_group]

        if all(len(g) == 0 for g in groups):
            break

    for group in groups:
        for score, words, _, _ in group:
            if words:
                completed.append((score, words))

    if not completed:
        return "(không có câu trả lời)"

    completed.sort(
        key=lambda x: length_penalized_score(x[0], len(x[1])),
        reverse=True
    )
    return " ".join(completed[0][1])

def show_image(image_pil, title=""):
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.imshow(image_pil)
    if title:
        ax.set_title(title, fontsize=12, pad=8)
    ax.axis("off")
    plt.tight_layout()
    plt.show()

# ── 6. VÒNG LẶP HỎI-ĐÁP ─────────────────────────────────────────────────────
total_beams = NUM_GROUPS * BEAMS_PER_GROUP
print("=" * 56)
print("  🖼️  HỆ THỐNG HỎI-ĐÁP TRỰC QUAN (VQA) - MÔ HÌNH A1")
print(f"  🔎  Diverse Beam Search  |  {NUM_GROUPS} nhóm × {BEAMS_PER_GROUP} beam = {total_beams} beam")
print(f"       max_len={MAX_LEN}  |  alpha={LENGTH_ALPHA}  |  gamma={DIVERSITY_GAMMA}")
print("=" * 56)
print("  Lệnh đặc biệt khi nhập câu hỏi:")
print("    📷  new   → upload ảnh mới")
print("    🚪  thoat → kết thúc chương trình")
print("=" * 56)

current_image = None

while True:
    print("\n HỆ THỐNG ĐÃ SẴN SÀNG")
    img_path = input("Nhập đường dẫn ảnh (hoặc 'thoat' để kết thúc): ").strip()

    if img_path.lower() in ["thoat", "exit", "quit"]:
        print("\n Đã dừng chương trình.")
        break

    if not os.path.exists(img_path):
        print(f" Không tìm thấy file tại đường dẫn: {img_path}")
        continue

    try:
        current_image = Image.open(img_path).convert("RGB")
        show_image(current_image, title=f"📷 {os.path.basename(img_path)}")
    except Exception as e:
        print(f" Không thể đọc ảnh: {e}")
        continue

    question = input(" Câu hỏi: ").strip()

    if question == "":
        print("  Vui lòng nhập câu hỏi.")
        continue

    answer = infer_diverse_beam(current_image, question)
    print("─" * 56)
    print(f"    {answer}")
    print("─" * 56)

!pip install -q bert-score transformers
!pip install -q rouge-score bert-score nltk transformers

import torch
import nltk
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from bert_score import score as bert_score
from tqdm.auto import tqdm

nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

def evaluate_vqa_metrics(model, val_dataset, vocab, device, max_len=15):
    # Lấy mô hình gốc ra khỏi DataParallel (nếu có)
    base_model = model.module if hasattr(model, 'module') else model
    base_model.eval()

    predictions_str = []
    references_str = []

    print("Đang chạy suy luận trên tập Validation với ViT + PhoBERT...")

    with torch.no_grad():
        for idx in tqdm(range(len(val_dataset)), desc="Dự đoán"):
            image, input_ids, attention_mask, answer_tensor = val_dataset[idx]

            img_tensor = image.unsqueeze(0).to(device)
            input_ids = input_ids.unsqueeze(0).to(device)
            attention_mask = attention_mask.unsqueeze(0).to(device)

            # SỬ DỤNG base_model THAY VÌ model
            h_d, c_d, features = base_model(img_tensor, input_ids, attention_mask)
            current_word_idx = torch.tensor([vocab.stoi["<SOS>"]]).to(device)
            pred_words = []

            for _ in range(max_len):
                # SỬ DỤNG base_model THAY VÌ model
                context, _ = base_model.attention(features, h_d[0])
                word_embed = base_model.embedding(current_word_idx)
                step_input = torch.cat([word_embed, context], dim=1)

                new_h, new_c = [], []
                curr_input = step_input
                for i, cell in enumerate(base_model.decoder_cell):
                    h_i, c_i = cell(curr_input, (h_d[i], c_d[i]))
                    new_h.append(h_i)
                    new_c.append(c_i)
                    curr_input = h_i

                h_d, c_d = new_h, new_c

                # SỬ DỤNG base_model THAY VÌ model
                logits = base_model.vocab_classifier(base_model.dropout(h_d[-1]))
                _, next_word_idx = torch.max(logits, dim=1)

                word = vocab.itos[next_word_idx.item()]
                if word == "<EOS>":
                    break
                pred_words.append(word)
                current_word_idx = next_word_idx

            predictions_str.append(" ".join(pred_words))

            ref_words = [vocab.itos[t.item()] for t in answer_tensor
                         if vocab.itos[t.item()] not in ["<SOS>", "<EOS>", "<PAD>"]]
            references_str.append(" ".join(ref_words))

    print("\n" + "="*55)
    print(" KẾT QUẢ ĐÁNH GIÁ CHI TIẾT (ViT + PhoBERT) ")
    print("="*55)

    nltk_preds = [pred.split() for pred in predictions_str]
    nltk_refs = [[ref.split()] for ref in references_str]
    chencherry = SmoothingFunction()

    bleu1 = corpus_bleu(nltk_refs, nltk_preds, weights=(1, 0, 0, 0), smoothing_function=chencherry.method1)
    print(f"1. BLEU-1 Score:       {bleu1 * 100:.2f} / 100")

    bleu4 = corpus_bleu(nltk_refs, nltk_preds, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=chencherry.method1)
    print(f"2. BLEU-4 Score:       {bleu4 * 100:.2f} / 100")

    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rouge_scores = [scorer.score(ref, pred)['rougeL'].fmeasure for pred, ref in zip(predictions_str, references_str)]
    avg_rouge = sum(rouge_scores) / len(rouge_scores) if rouge_scores else 0
    print(f"3. ROUGE-L F1:         {avg_rouge * 100:.2f} / 100")

    meteor_scores = [meteor_score([ref.split()], pred.split()) for pred, ref in zip(predictions_str, references_str)]
    avg_meteor = sum(meteor_scores) / len(meteor_scores) if meteor_scores else 0
    print(f"4. METEOR Score:       {avg_meteor * 100:.2f} / 100")

    print("\nĐang tính toán BERTScore...")
    P, R, F1 = bert_score(predictions_str, references_str, lang="vi", model_type="bert-base-multilingual-cased", verbose=False)
    avg_bert_f1 = F1.mean().item()
    print(f"5. BERTScore (F1):     {avg_bert_f1 * 100:.2f} / 100")

    print("="*55)

# Chạy lại hàm đánh giá
evaluate_vqa_metrics(model, val_dataset, vocab, device)


import os
import json
import torch
import pandas as pd
from tqdm.auto import tqdm

# ── 1. THAM SỐ ───────────────────────────────────────────────────────────────
NUM_SAMPLES    = len(train_dataset)   # Số mẫu val muốn chạy qua (tăng/giảm tuỳ ý)
SIMILARITY_THR = 0.5   # Tỉ lệ từ trùng tối đa để coi là "sai"
               # 0.0 = chỉ lấy khi AI sai hoàn toàn
               # 0.5 = lấy khi AI đúng < 50% số từ so với ground truth

# ── 2. HÀM TIỆN ÍCH ──────────────────────────────────────────────────────────
def token_overlap_ratio(pred: str, ref: str) -> float:
    """
    Tỉ lệ từ trùng giữa pred và ref (Precision phía pred).
    = |{từ trong pred} ∩ {từ trong ref}| / max(|pred|, 1)
    """
    pred_tokens = set(pred.lower().split())
    ref_tokens  = set(ref.lower().split())
    if not pred_tokens:
        return 0.0
    return len(pred_tokens & ref_tokens) / len(pred_tokens)

def is_wrong(pred: str, ref: str, threshold: float = SIMILARITY_THR) -> bool:
    """Trả về True nếu câu trả lời của AI bị coi là sai/không đủ tốt."""
    if not pred or pred.strip() == "(không có câu trả lời)":
        return True
    return token_overlap_ratio(pred, ref) < threshold

# ── 3. VÒNG LẶP THU THẬP ─────────────────────────────────────────────────────
print("Bắt đầu thu thập Preference Data từ mô hình SFT A1...")
print(f"   Số mẫu  : {NUM_SAMPLES}")
print(f"   Ngưỡng  : overlap < {SIMILARITY_THR} → coi là rejected\n")

inference_model.eval()

preference_data = []   # [{prompt, chosen, rejected, overlap, img_path}, ...]
n_correct = 0
n_rejected = 0
n_empty    = 0

indices = list(range(len(val_dataset)))[:NUM_SAMPLES]

for idx in tqdm(indices, desc="Thu thập preference"):
    image_tensor, input_ids, attention_mask, answer_tensor = val_dataset[idx]

    # ── Lấy ground truth ───────────────────────────────────────────────────
    ref_words = [
        vocab.itos[t.item()] for t in answer_tensor
        if vocab.itos[t.item()] not in ["<SOS>", "<EOS>", "<PAD>"]
    ]
    chosen = " ".join(ref_words)

    # ── Lấy câu hỏi gốc từ val_df ─────────────────────────────────────────
    row     = val_df.iloc[idx]
    prompt  = row["question"]
    img_rel = row["image_path"]

    # ── Chạy inference ─────────────────────────────────────────────────────
    img_t  = image_tensor.unsqueeze(0).to(device)
    iid    = input_ids.unsqueeze(0).to(device)
    amask  = attention_mask.unsqueeze(0).to(device)

    with torch.no_grad():
        h_d, c_d, features = inference_model(img_t, iid, amask)

    # Dùng lại hàm infer_diverse_beam từ cell Inference (đã định nghĩa ở Cell 7)
    from PIL import Image as PILImage
    import torchvision.transforms.functional as TF

    # Chuyển tensor ảnh về PIL để truyền vào infer_diverse_beam
    img_pil = TF.to_pil_image(
        (image_tensor * 0.5 + 0.5).clamp(0, 1)   # de-normalize [0.5, 0.5, 0.5]
    )
    rejected_raw = infer_diverse_beam(img_pil, prompt)
    rejected = rejected_raw.strip()

    # ── Phân loại ─────────────────────────────────────────────────────────
    overlap = token_overlap_ratio(rejected, chosen)

    if not rejected or rejected == "(không có câu trả lời)":
        n_empty += 1

    if is_wrong(rejected, chosen):
        n_rejected += 1
        preference_data.append({
            "prompt"   : prompt,
            "chosen"   : chosen,
            "rejected" : rejected,
            "overlap"  : round(overlap, 4),
            "img_path" : img_rel,
        })
    else:
        n_correct += 1

# ── 4. THỐNG KÊ ──────────────────────────────────────────────────────────────
print(f"\n{'='*52}")
print(f"KẾT QUẢ THU THẬP PREFERENCE DATA")
print(f"{'='*52}")
print(f"Tổng mẫu chạy        : {NUM_SAMPLES}")
print(f"AI trả lời đúng   : {n_correct}  ({n_correct/NUM_SAMPLES*100:.1f}%)")
print(f"AI trả lời sai    : {n_rejected}  ({n_rejected/NUM_SAMPLES*100:.1f}%)")
print(f"AI trả lời rỗng   : {n_empty}  ({n_empty/NUM_SAMPLES*100:.1f}%)")
print(f"Cặp preference lưu: {len(preference_data)}")
print(f"{'='*52}")

# ── 5. LƯU KẾT QUẢ ───────────────────────────────────────────────────────────
JSON_PATH = os.path.join(WEIGHTS_DIR, "preference_data_A1.json")
CSV_PATH  = os.path.join(WEIGHTS_DIR, "preference_data_A1.csv")

with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(preference_data, f, ensure_ascii=False, indent=2)

df_pref = pd.DataFrame(preference_data)
df_pref.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")

print(f"\nĐã lưu JSON : {JSON_PATH}")
print(f"Đã lưu CSV  : {CSV_PATH}")

# ── 6. XEM THỬ MỘT VÀI MẪU ──────────────────────────────────────────────────
print(f"\n{'─'*52}")
print(f"VÍ DỤ MỘT VÀI CẶP PREFERENCE (3 mẫu đầu)")
print(f"{'─'*52}")
for i, sample in enumerate(preference_data[:3]):
    print(f"\n  [{i+1}] Câu hỏi : {sample['prompt']}")
    print(f"       Chosen  : {sample['chosen']}")
    print(f"       Rejected: {sample['rejected']}")
    print(f"       Overlap : {sample['overlap']}")
print(f"{'─'*52}")
print("\nPreference data sẵn sàng để dùng cho DPO / RLHF!")