# -*- coding: utf-8 -*-
"""a2_transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/truongminh3105/a2-transformer.31d2b25c-2f7e-4f01-891b-3c6fa848a654.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T092525Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D77e164616559ad676b0fdf90c40eb673726bc3df111184e9c748ccc6fd2940cfa73ae242643a3b5ddeed7a66a97b2978907361a49aae1d1898ddf51506a50e6512532e15cc8a836fb44afef18f1c809b6076a190db0d724bca3a22011b86c0b57ea98e6c71740132f9671c24849d603ab216a7e1723d307a06c1c3e6784f41cb19e38ea92b3a6217bf41ebf7d36d456d8a3bc5783eb2493939dbaf6e7255def77d4e433da6bbdb4bfc0af1d9f75bd8a3e84fa3f46bd3942e8056b4095726e2f4247aab4d9e1df282b9539308d6938b1a897fa251636ad4a42efab9c6a18cea806dd66f66f3b437b055f7818e3903db3db70b62a34df6137c839a32212f442de8
"""

from huggingface_hub import login



!pip install gradio torch torchvision transformers peft accelerate bitsandbytes sentencepiece protobuf timm nltk rouge-score bert-score pandas tabulate
!pip install -r /kaggle/input/datasets/truongminh3105/vqa-vnf-dataset/requirements.txt
!pip install -U bitsandbytes

import os
import re
import json
import torch
import torch.nn as nn
import pandas as pd
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm

# Cấu hình thiết bị cho 2 GPU T4
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
n_gpu = torch.cuda.device_count()
print(f"Thiết bị: {device} | Số lượng GPU phát hiện: {n_gpu}")

# ==========================================
# CẤU HÌNH SIÊU THAM SỐ
# ==========================================
BATCH_SIZE = 32
NUM_WORKERS = 4
EPOCHS = 5
LEARNING_RATE = 2e-5


DATASET_ROOT = '/kaggle/input/datasets/truongminh3105/vqa-vnf-dataset/dataset'

TRAIN_JSON = os.path.join(DATASET_ROOT, 'annotations/train_augmented.json')
VAL_JSON = os.path.join(DATASET_ROOT, 'annotations/val.json')
TEST_JSON = os.path.join(DATASET_ROOT, 'annotations/test.json')

WEIGHTS_DIR = '/kaggle/working/weights'
os.makedirs(WEIGHTS_DIR, exist_ok=True)

def parse_json_to_df(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    records = []
    for item in data:
        img_path = item['image_path'] 
        for qa in item['qa_pairs']:
            records.append({
                'image_path': img_path,
                'question': qa['question'],
                'answer': str(qa['answer'])
            })
    return pd.DataFrame(records)

print("Đang đọc dữ liệu JSON...")
train_df = parse_json_to_df(TRAIN_JSON)
val_df = parse_json_to_df(VAL_JSON)
test_df = parse_json_to_df(TEST_JSON) 

print(f"Số lượng QA Train: {len(train_df)}")
print(f"Số lượng QA Val: {len(val_df)}")
print(f"Số lượng QA Test: {len(test_df)}")

class Vocabulary:
    def __init__(self, freq_threshold=2):
        self.freq_threshold = freq_threshold
        self.itos = {0: "<PAD>", 1: "<SOS>", 2: "<EOS>", 3: "<UNK>"}
        self.stoi = {"<PAD>": 0, "<SOS>": 1, "<EOS>": 2, "<UNK>": 3}
        self.idx = 4
    def __len__(self): return len(self.itos)
    @staticmethod
    def tokenizer(text):
        return re.sub(r'[^\w\s]', '', str(text).lower()).split()
    def build_vocabulary(self, sentence_list):
        frequencies = Counter()
        for sentence in sentence_list:
            for word in self.tokenizer(sentence):
                frequencies[word] += 1
        for word, count in frequencies.items():
            if count >= self.freq_threshold:
                self.stoi[word] = self.idx
                self.itos[self.idx] = word
                self.idx += 1
    def numericalize(self, text):
        tokens = self.tokenizer(text)
        return [self.stoi.get(t, self.stoi["<UNK>"]) for t in tokens]

all_text = train_df['question'].tolist() + train_df['answer'].tolist() + \
           val_df['question'].tolist() + val_df['answer'].tolist()

vocab = Vocabulary(freq_threshold=2)
vocab.build_vocabulary(all_text)
print(f"Kích thước từ vựng: {len(vocab)}")

import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

class VQA_JSON_Dataset(Dataset):
    def __init__(self, df, dataset_root, tokenizer, vocab, transform=None, max_len=50):
        self.df = df
        self.dataset_root = dataset_root
        self.tokenizer = tokenizer
        self.vocab = vocab
        self.transform = transform
        self.max_len = max_len

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        img_path = os.path.join(self.dataset_root, row['image_path'])

        try:
            image = Image.open(img_path).convert('RGB')
        except:
            image = Image.new('RGB', (224, 224), (0, 0, 0))

        if self.transform: image = self.transform(image)

        encoded_q = self.tokenizer(row['question'], truncation=True, max_length=self.max_len,
                                   padding='max_length', return_tensors='pt')

        ans_tokens = [self.vocab.stoi["<SOS>"]] + self.vocab.numericalize(row['answer']) + [self.vocab.stoi["<EOS>"]]

        return image, encoded_q['input_ids'].squeeze(0), encoded_q['attention_mask'].squeeze(0), torch.tensor(ans_tokens)

def collate_fn(batch):
    images, ids, masks, answers = zip(*batch)
    return torch.stack(images), torch.stack(ids), torch.stack(masks), pad_sequence(answers, batch_first=True, padding_value=0)

train_trans = transforms.Compose([
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

val_test_trans = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

train_dataset = VQA_JSON_Dataset(train_df, DATASET_ROOT, tokenizer, vocab, transform=train_trans)
val_dataset = VQA_JSON_Dataset(val_df, DATASET_ROOT, tokenizer, vocab, transform=val_test_trans)
test_dataset = VQA_JSON_Dataset(test_df, DATASET_ROOT, tokenizer, vocab, transform=val_test_trans) # Thêm Test

loader_kwargs = {'batch_size': BATCH_SIZE, 'num_workers': NUM_WORKERS, 'collate_fn': collate_fn, 'pin_memory': True}

train_loader = DataLoader(train_dataset, shuffle=True, **loader_kwargs)
val_loader = DataLoader(val_dataset, shuffle=False, **loader_kwargs)
test_loader = DataLoader(test_dataset, shuffle=False, **loader_kwargs) 

import math
import torch
import torch.nn as nn
from transformers import AutoModel

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=100):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))
    def forward(self, x): return x + self.pe[:, :x.size(1), :]

class VQA_A2_Model(nn.Module):
    def __init__(self, vocab_size, embed_size=768, nhead=8, num_layers=4):
        super().__init__()
        self.vit = AutoModel.from_pretrained("google/vit-base-patch16-224-in21k")
        self.phobert = AutoModel.from_pretrained("vinai/phobert-base")
        self.embedding = nn.Embedding(vocab_size, embed_size, padding_idx=0)
        self.pos_encoder = PositionalEncoding(embed_size)

        decoder_layer = nn.TransformerDecoderLayer(d_model=embed_size, nhead=nhead,
                                                   dim_feedforward=embed_size*4, batch_first=True)
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_layers)
        self.classifier = nn.Linear(embed_size, vocab_size)


    def generate_mask(self, sz, device):
        mask = (torch.triu(torch.ones(sz, sz, device=device)) == 1).transpose(0, 1)
        mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
        return mask

    def forward(self, images, input_ids, attention_mask, answers=None):
        img_feats = self.vit(pixel_values=images).last_hidden_state[:, 1:, :]
        txt_feats = self.phobert(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state
        memory = torch.cat([img_feats, txt_feats], dim=1)

        if answers is not None:
            tgt = self.pos_encoder(self.embedding(answers))
            mask = self.generate_mask(answers.size(1), images.device)
            out = self.decoder(tgt=tgt, memory=memory, tgt_mask=mask)
            return self.classifier(out)
        return memory

model = VQA_A2_Model(len(vocab)).to(device)
if n_gpu > 1:
    model = nn.DataParallel(model)
    print("🚀 Đang chạy trên song song 2 GPU!")

import os
import shutil
os.makedirs('/kaggle/working/weights', exist_ok=True)

source_file = '/kaggle/input/datasets/truongminh3105/vqa-model-a2/vqa_model_A2_parallel.pth'

destination_file = '/kaggle/working/weights/vqa_model_A2_parallel.pth'

if not os.path.exists(destination_file):
    shutil.copy(source_file, destination_file)
    print("Đã copy file model sang thư mục working!")
else:
    print("File model đã có sẵn trong working.")

import torch.optim as optim
import torch.nn.functional as F
from transformers import get_cosine_schedule_with_warmup

optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
total_steps = len(train_loader) * EPOCHS
scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=int(0.1*total_steps), num_training_steps=total_steps)

best_loss = float('inf')
MODEL_PATH = os.path.join(WEIGHTS_DIR, 'vqa_model_A2_parallel.pth')

for epoch in range(EPOCHS):
    model.train()
    total_train_loss = 0
    for imgs, ids, masks, ans in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        imgs, ids, masks, ans = imgs.to(device), ids.to(device), masks.to(device), ans.to(device)

        optimizer.zero_grad()
        outputs = model(imgs, ids, masks, ans[:, :-1])
        loss = F.cross_entropy(outputs.reshape(-1, outputs.shape[-1]),
                               ans[:, 1:].reshape(-1), ignore_index=0)

        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_train_loss += loss.item()

    avg_loss = total_train_loss / len(train_loader)
    print(f"Epoch {epoch+1} | Loss: {avg_loss:.4f}")

    if avg_loss < best_loss:
        best_loss = avg_loss
        state_dict = model.module.state_dict() if n_gpu > 1 else model.state_dict()
        torch.save(state_dict, MODEL_PATH)

import matplotlib.pyplot as plt
import os

plt.figure(figsize=(10, 6))

epochs_run = len(history_train_loss)

plt.plot(range(1, epochs_run + 1), history_train_loss, label='Training Loss', color='teal', marker='o')
plt.plot(range(1, epochs_run + 1), history_val_loss, label='Validation Loss', color='darkorange', marker='s')

plt.title('Biểu đồ Loss huấn luyện VQA (Mô hình A2: ViT + PhoBERT + Transformer)', fontsize=14, pad=15)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Label Smoothed NLL Loss', fontsize=12)
plt.xticks(range(1, epochs_run + 1))
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)

PLOT_SAVE_PATH = os.path.join(WEIGHTS_DIR, 'loss_plot_A2_vit_phobert_transformer.png')
plt.savefig(PLOT_SAVE_PATH, dpi=300, bbox_inches='tight')
print(f"Đã lưu biểu đồ A2 vào: {PLOT_SAVE_PATH}")

plt.show()

import torch
import torch.nn as nn
from PIL import Image
import matplotlib.pyplot as plt
import os
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def predict_a2_transformer(image_path, question_text, model, vocab, device, max_len=15):
    A2_MODEL_PATH = os.path.join(WEIGHTS_DIR, 'vqa_model_A2_vit_phobert_transformer.pth')

    if os.path.exists(A2_MODEL_PATH):
        model.load_state_dict(torch.load(A2_MODEL_PATH, map_location=device))
        model.eval()
    else:
        print(f"Lỗi: Không tìm thấy file tại {A2_MODEL_PATH}")
        return

    image = Image.open(image_path).convert("RGB")
    img_tensor = val_transform(image).unsqueeze(0).to(device)

    encoded_q = tokenizer(question_text, return_tensors='pt', truncation=True, max_length=50)
    input_ids = encoded_q['input_ids'].to(device)
    attention_mask = encoded_q['attention_mask'].to(device)

    predicted_words = []

    with torch.no_grad():
        memory = model(img_tensor, input_ids, attention_mask, answers=None)

        current_tokens = [vocab.stoi["<SOS>"]]

        for _ in range(max_len):
            tgt_tensor = torch.tensor(current_tokens).unsqueeze(0).to(device)

            tgt_embed = model.embedding(tgt_tensor)
            tgt_embed = model.pos_encoder(tgt_embed)

            tgt_mask = model.generate_square_subsequent_mask(tgt_tensor.size(1)).to(device)

            output = model.transformer_decoder(
                tgt=tgt_embed,
                memory=memory,
                tgt_mask=tgt_mask
            )

            logits = model.vocab_classifier(output)
            next_token_logits = logits[0, -1, :]
            _, next_token = torch.max(next_token_logits, dim=0)

            word = vocab.itos[next_token.item()]

            if word == "<EOS>":
                break

            predicted_words.append(word)
            current_tokens.append(next_token.item())

    plt.figure(figsize=(6, 6))
    plt.imshow(image)
    plt.title(f"Q: {question_text}")
    plt.axis('off')
    plt.show()

    print(f"AI Trả lời: {' '.join(predicted_words)}")
    return predicted_words

test_row = df.sample(1).iloc[0]
img_name = test_row['image_path'].split('images/')[-1] if test_row['image_path'].startswith('images/') else test_row['image_path']
test_img_path = os.path.join(IMG_DIR, img_name)

pred = predict_a2_transformer(test_img_path, test_row['question'], model, vocab, device)
print(f"Đáp án đúng gốc: {test_row['answer']}")


import os
import io
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from PIL import Image
from google.colab import files
from transformers import AutoTokenizer

# ── 0. HÀM HỖ TRỢ HIỂN THỊ (Sửa lỗi NameError) ─────────────────────────────
def show_image(image_pil, title=""):
    """Hiển thị ảnh bằng matplotlib."""
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.imshow(image_pil)
    if title:
        ax.set_title(title, fontsize=12, pad=8)
    ax.axis("off")
    plt.tight_layout()
    plt.show()

# ── 1. KHỞI TẠO MÔ HÌNH VÀ TẢI TRỌNG SỐ ──────────────────────────────
print(" Đang khởi tạo mô hình A2 và nạp trọng số...")

EMBED_SIZE = 768
NHEAD      = 8
NUM_LAYERS = 4

inference_model = VQA_A2_Transformer_Model(
    vocab_size   = len(vocab),
    embed_size   = EMBED_SIZE,
    nhead        = NHEAD,
    num_layers   = NUM_LAYERS,
    dropout_rate = 0.0
).to(device)

MODEL_SAVE_PATH = os.path.join(WEIGHTS_DIR, 'vqa_model_A2_vit_phobert_transformer.pth')

if os.path.exists(MODEL_SAVE_PATH):
    inference_model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=device))
    inference_model.eval()
    print(f" Đã nạp thành công trọng số A2.")
else:
    print(f" Cảnh báo: Không tìm thấy file trọng số tại {MODEL_SAVE_PATH}")

infer_tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

# ── 2. THAM SỐ DIVERSE BEAM SEARCH ───────────────────────────────────────────
NUM_GROUPS      = 3
BEAMS_PER_GROUP = 2
MAX_LEN         = 15
LENGTH_ALPHA    = 0.7
DIVERSITY_GAMMA = 0.5

# ── 3. LOGIC GIẢI MÃ TRANSFORMER ─────────────────────────────────────────────
def transformer_step(tgt_indices, memory):
    """Thực hiện một bước giải mã qua Transformer Decoder."""
    tgt_tensor = torch.tensor(tgt_indices).unsqueeze(0).to(device)

    tgt_embed = inference_model.embedding(tgt_tensor)
    tgt_embed = inference_model.pos_encoder(tgt_embed)

    sz = tgt_tensor.size(1)
    mask = inference_model.generate_square_subsequent_mask(sz).to(device)

    # Decoder lấy thông tin từ Memory (Ảnh + Text Encoder)
    output = inference_model.transformer_decoder(
        tgt=tgt_embed,
        memory=memory,
        tgt_mask=mask
    )

    logits = inference_model.vocab_classifier(output[:, -1, :])
    return F.log_softmax(logits, dim=1)

def length_penalized_score(score, length, alpha=LENGTH_ALPHA):
    return score / (length ** alpha) if length > 0 else score

# ── 4. HÀM DỰ ĐOÁN CHÍNH ─────────────────────────────────────────────────────
def infer_vqa_a2_diverse(image_pil, question_text):
    img_tensor = val_transform(image_pil).unsqueeze(0).to(device)

    encoded_q = infer_tokenizer(
        question_text, return_tensors='pt',
        truncation=True, max_length=50, padding='max_length'
    )
    input_ids = encoded_q['input_ids'].to(device)
    attention_mask = encoded_q['attention_mask'].to(device)

    with torch.no_grad():
        memory = inference_model(img_tensor, input_ids, attention_mask, answers=None)

    sos_idx = vocab.stoi["<SOS>"]
    groups = [[(0.0, [sos_idx])] for _ in range(NUM_GROUPS)]
    completed = []

    for _ in range(MAX_LEN):
        tokens_chosen_this_step = []
        for g in range(NUM_GROUPS):
            candidates = []
            for score, tokens in groups[g]:
                if tokens[-1] == vocab.stoi["<EOS>"]: continue

                log_prob = transformer_step(tokens, memory)

                penalized_prob = log_prob[0].clone()
                for p_idx in tokens_chosen_this_step:
                    penalized_prob[p_idx] -= DIVERSITY_GAMMA

                topk_scores, topk_idxs = penalized_prob.topk(BEAMS_PER_GROUP)

                for lp, idx in zip(topk_scores, topk_idxs):
                    t_idx = idx.item()
                    new_score = score + log_prob[0][t_idx].item()
                    new_tokens = tokens + [t_idx]

                    if t_idx == vocab.stoi["<EOS>"]:
                        completed.append((new_score, new_tokens))
                    else:
                        candidates.append((new_score, new_tokens))
                        tokens_chosen_this_step.append(t_idx)

            if not candidates: continue
            candidates.sort(key=lambda x: length_penalized_score(x[0], len(x[1])), reverse=True)
            groups[g] = candidates[:BEAMS_PER_GROUP]

        if all(len(g) == 0 or g[0][1][-1] == vocab.stoi["<EOS>"] for g in groups): break

    for g in groups:
        for s, t in g: completed.append((s, t))

    if not completed: return "..."
    completed.sort(key=lambda x: length_penalized_score(x[0], len(x[1])), reverse=True)

    res = [vocab.itos[t] for t in completed[0][1]
           if t not in [vocab.stoi["<SOS>"], vocab.stoi["<EOS>"], vocab.stoi["<PAD>"]]]
    return " ".join(res)

# ── 5. VÒNG LẶP GIAO DIỆN ───────────────────────────────────────────────────
print("=" * 60)
print("  DEMO VQA A2: ViT + PhoBERT + Transformer Decoder")
print("=" * 60)

current_image = None

while True:
    if current_image is None:
        print("\n Tải lên ảnh để bắt đầu:")
        uploaded = files.upload()
        if not uploaded: break
        filename = list(uploaded.keys())[0]
        current_image = Image.open(io.BytesIO(uploaded[filename])).convert("RGB")
        show_image(current_image, title=f"📷 {filename}")

    question = input("\n Câu hỏi (new = ảnh mới | thoat = thoát): ").strip()
    if question.lower() in ["thoat", "exit", "quit"]: break
    if question.lower() == "new":
        current_image = None
        continue
    if question == "": continue

    answer = infer_vqa_a2_diverse(current_image, question)
    print("─" * 60)
    print(f" {answer}")
    print("─" * 60)

!pip install -q bert-score transformers
!pip install -q rouge-score bert-score nltk transformers

import torch
import nltk
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from bert_score import score as bert_score
from tqdm.auto import tqdm

nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

def evaluate_vqa_metrics(model, val_dataset, vocab, device, max_len=15):
    model.eval()
    predictions_str = []
    references_str = []

    print("Đang chạy suy luận trên tập Validation với mô hình A2...")

    with torch.no_grad():
        for idx in tqdm(range(len(val_dataset)), desc="Dự đoán"):
            image, input_ids, attention_mask, answer_tensor = val_dataset[idx]

            img_tensor = image.unsqueeze(0).to(device)
            input_ids = input_ids.unsqueeze(0).to(device)
            attention_mask = attention_mask.unsqueeze(0).to(device)

            memory = model(img_tensor, input_ids, attention_mask, answers=None)

            current_tokens = [vocab.stoi["<SOS>"]]
            pred_words = []

            for _ in range(max_len):
                tgt_tensor = torch.tensor(current_tokens).unsqueeze(0).to(device)

                tgt_embed = model.embedding(tgt_tensor)
                tgt_embed = model.pos_encoder(tgt_embed)

                tgt_mask = model.generate_square_subsequent_mask(tgt_tensor.size(1)).to(device)

                output = model.transformer_decoder(
                    tgt=tgt_embed,
                    memory=memory,
                    tgt_mask=tgt_mask
                )

                logits = model.vocab_classifier(output)
                next_token_logits = logits[0, -1, :]
                _, next_token = torch.max(next_token_logits, dim=0)

                word = vocab.itos[next_token.item()]

                if word == "<EOS>":
                    break

                pred_words.append(word)
                current_tokens.append(next_token.item())

            predictions_str.append(" ".join(pred_words))

            ref_words = [vocab.itos[t.item()] for t in answer_tensor
                         if vocab.itos[t.item()] not in ["<SOS>", "<EOS>", "<PAD>"]]
            references_str.append(" ".join(ref_words))

    print("\n" + "="*55)
    print(" KẾT QUẢ ĐÁNH GIÁ CHI TIẾT (MÔ HÌNH A2) ")
    print("="*55)

    nltk_preds = [pred.split() for pred in predictions_str]
    nltk_refs = [[ref.split()] for ref in references_str]
    chencherry = SmoothingFunction()

    bleu1 = corpus_bleu(nltk_refs, nltk_preds, weights=(1, 0, 0, 0), smoothing_function=chencherry.method1)
    print(f"1. BLEU-1 Score:       {bleu1 * 100:.2f} / 100")

    bleu4 = corpus_bleu(nltk_refs, nltk_preds, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=chencherry.method1)
    print(f"2. BLEU-4 Score:       {bleu4 * 100:.2f} / 100")

    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rouge_scores = [scorer.score(ref, pred)['rougeL'].fmeasure for pred, ref in zip(predictions_str, references_str)]
    avg_rouge = sum(rouge_scores) / len(rouge_scores) if rouge_scores else 0
    print(f"3. ROUGE-L F1:         {avg_rouge * 100:.2f} / 100")

    meteor_scores = [meteor_score([ref.split()], pred.split()) for pred, ref in zip(predictions_str, references_str)]
    avg_meteor = sum(meteor_scores) / len(meteor_scores) if meteor_scores else 0
    print(f"4. METEOR Score:       {avg_meteor * 100:.2f} / 100")

    print("\nĐang tính toán BERTScore ngữ nghĩa...")
    P, R, F1 = bert_score(predictions_str, references_str, lang="vi", model_type="bert-base-multilingual-cased", verbose=False)
    avg_bert_f1 = F1.mean().item()
    print(f"5. BERTScore (F1):     {avg_bert_f1 * 100:.2f} / 100")

    print("="*55)

evaluate_vqa_metrics(model, val_dataset, vocab, device)


import os
import json
import torch
import pandas as pd
from tqdm.auto import tqdm
from PIL import Image as PILImage
import torchvision.transforms.functional as TF

# ── 1. THAM SỐ ───────────────────────────────────────────────────────────────
NUM_SAMPLES    = len(train_dataset)   # Số mẫu val muốn chạy qua (tăng/giảm tuỳ ý)
SIMILARITY_THR = 0.5   # Tỉ lệ từ trùng tối đa để coi là "sai"

# ── 2. HÀM TIỆN ÍCH ──────────────────────────────────────────────────────────
def token_overlap_ratio(pred: str, ref: str) -> float:
    """
    Tỉ lệ từ trùng giữa pred và ref.
    """
    pred_tokens = set(pred.lower().split())
    ref_tokens  = set(ref.lower().split())
    if not pred_tokens:
        return 0.0
    return len(pred_tokens & ref_tokens) / len(pred_tokens)

def is_wrong(pred: str, ref: str, threshold: float = SIMILARITY_THR) -> bool:

    if not pred or pred.strip() in ["(không có câu trả lời)", "..."]:
        return True
    return token_overlap_ratio(pred, ref) < threshold

# ── 3. VÒNG LẶP THU THẬP ─────────────────────────────────────────────────────
print("Bắt đầu thu thập Preference Data từ mô hình SFT A2 (Transformer)...")
print(f"   Số mẫu  : {NUM_SAMPLES}")
print(f"   Ngưỡng  : overlap < {SIMILARITY_THR} → coi là rejected\n")

inference_model.eval()

preference_data = []
n_correct  = 0
n_rejected = 0
n_empty    = 0

indices = list(range(len(val_dataset)))[:NUM_SAMPLES]

for idx in tqdm(indices, desc="Thu thập preference A2"):
    image_tensor, input_ids, attention_mask, answer_tensor = val_dataset[idx]

    # ── Lấy ground truth ───────────────────────────────────────────────────
    ref_words = [
        vocab.itos[t.item()] for t in answer_tensor
        if vocab.itos[t.item()] not in ["<SOS>", "<EOS>", "<PAD>"]
    ]
    chosen = " ".join(ref_words)

    # ── Lấy câu hỏi gốc từ val_df ─────────────────────────────────────────
    row     = val_df.iloc[idx]
    prompt  = row["question"]
    img_rel = row["image_path"]

    # ── Chạy inference A2 ──────────────────────────────────────────────────
    # Chuyển tensor ảnh về PIL để truyền vào infer_vqa_a2_diverse
    img_pil = TF.to_pil_image(
        (image_tensor * 0.5 + 0.5).clamp(0, 1)   # de-normalize [0.5, 0.5, 0.5]
    )

    try:
        # Gọi hàm inference của Transformer
        rejected_raw = infer_vqa_a2_diverse(img_pil, prompt)
        rejected = rejected_raw.strip()
    except Exception as e:
        print(f"Lỗi inference ở ảnh {img_rel}: {e}")
        rejected = ""

    # ── Phân loại ─────────────────────────────────────────────────────────
    overlap = token_overlap_ratio(rejected, chosen)

    if not rejected or rejected in ["(không có câu trả lời)", "..."]:
        n_empty += 1

    if is_wrong(rejected, chosen):
        n_rejected += 1
        preference_data.append({
            "prompt"   : prompt,
            "chosen"   : chosen,
            "rejected" : rejected,
            "overlap"  : round(overlap, 4),
            "img_path" : img_rel,
        })
    else:
        n_correct += 1

# ── 4. THỐNG KÊ ──────────────────────────────────────────────────────────────
print(f"\n{'='*52}")
print(f"KẾT QUẢ THU THẬP PREFERENCE DATA (MÔ HÌNH A2)")
print(f"{'='*52}")
print(f"Tổng mẫu chạy        : {NUM_SAMPLES}")
print(f"AI trả lời đúng   : {n_correct}  ({n_correct/NUM_SAMPLES*100:.1f}%)")
print(f"AI trả lời sai    : {n_rejected}  ({n_rejected/NUM_SAMPLES*100:.1f}%)")
print(f"AI trả lời rỗng   : {n_empty}  ({n_empty/NUM_SAMPLES*100:.1f}%)")
print(f"Cặp preference lưu: {len(preference_data)}")
print(f"{'='*52}")

# ── 5. LƯU KẾT QUẢ ───────────────────────────────────────────────────────────
JSON_PATH = os.path.join(WEIGHTS_DIR, "preference_data_A2.json")
CSV_PATH  = os.path.join(WEIGHTS_DIR, "preference_data_A2.csv")

with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(preference_data, f, ensure_ascii=False, indent=2)

df_pref = pd.DataFrame(preference_data)
df_pref.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")

print(f"\nĐã lưu JSON : {JSON_PATH}")
print(f"Đã lưu CSV  : {CSV_PATH}")

# ── 6. XEM THỬ MỘT VÀI MẪU ──────────────────────────────────────────────────
print(f"\n{'─'*52}")
print(f"VÍ DỤ MỘT VÀI CẶP PREFERENCE A2 (3 mẫu đầu)")
print(f"{'─'*52}")
for i, sample in enumerate(preference_data[:3]):
    print(f"\n  [{i+1}] Câu hỏi : {sample['prompt']}")
    print(f"       Chosen  : {sample['chosen']}")
    print(f"       Rejected: {sample['rejected']}")
    print(f"       Overlap : {sample['overlap']}")
print(f"{'─'*52}")
print("\nPreference data (A2) sẵn sàng để dùng cho DPO / RLHF!")