# -*- coding: utf-8 -*-
"""b2-finetune

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/baole1510/b2-finetune.ce14ffba-7fc2-410b-858d-6ee1f1ec2c68.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T141304Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D756e2ea8f0a938913c23a86e02a81e969d5b959df9a39ed9cfc534888d97953aa1c9bd841e4c69c97ed0b8f95a3bd704b776bab4a61d449e34a2195bdf58e221c188369279e289643eaa25e17af1da56351b27881bbc30e749feab176a8672627f5de2b0da06efea77f35b97ca3936ee69fae5f285847228a26305f7d3dd7247a2b4cf5c244059e4849745973b457dda0852709d379103b169e766e71c146c9cfc42ddeb5db338b6522de7874195775800d3db499e5189d89d45450ad780683fa295b586c929be6401b92696952bc4a71997f0ab0ce3e4efed1b6df547391c255b63918a4b739db9b5f49b5a20a75e26392f83afc81c2a88e071016d5b073b90
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
truongminh3105_vqa_vnf_dataset_path = kagglehub.dataset_download('truongminh3105/vqa-vnf-dataset')

print('Data source import complete.')

# Cài đặt các thư viện cần thiết (nhất quán với B1 + thêm peft)
!pip install -q deep-translator
!pip install -q bert-score rouge-score nltk
!pip install -U transformers peft bert-score accelerate bitsandbytes rouge-score

!pip install -q -U bitsandbytes transformers peft accelerate
!pip install -q deep-translator bert-score rouge-score nltk Pillow tqdm pandas

print("✅ Đã cài đặt xong bộ thư viện bản mới nhất!")

import os
import pandas as pd
import json
import torch
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt

# Đường dẫn Kaggle (Điều chỉnh theo tên dataset bạn upload/add vào notebook)
INPUT_DIR = '/kaggle/input/datasets/truongminh3105/vqa-vnf-dataset/dataset'
WORKING_DIR = '/kaggle/working/'

# Thư mục lưu kết quả
RESULTS_DIR = os.path.join(WORKING_DIR, 'results_B2')
CKPT_DIR = os.path.join(WORKING_DIR, 'checkpoints_B2')
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(CKPT_DIR, exist_ok=True)

# Tự động chọn thiết bị (Hỗ trợ Multi-GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
num_gpus = torch.cuda.device_count()
print(f"Thiết bị: {device} | Số lượng GPU: {num_gpus}")

def parse_vqa_json(json_path, img_folder):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    flattened_data = []
    for item in data:
        image_id = item['image_id']
        # Kiểm tra phần mở rộng file (jpg/png) tùy dataset của bạn
        image_path = os.path.join(img_folder, f"{image_id}.jpg")

        for qa in item['qa_pairs']:
            flattened_data.append({
                'image_path': image_path,
                'question': qa['question'],
                'answer': qa['answer']
            })

    return pd.DataFrame(flattened_data)

# Tải dữ liệu trực tiếp từ các file đã chia sẵn
train_df = parse_vqa_json(f"{INPUT_DIR}/annotations/train.json", f"{INPUT_DIR}/Images/train")
val_df   = parse_vqa_json(f"{INPUT_DIR}/annotations/val.json", f"{INPUT_DIR}/Images/val")
test_df  = parse_vqa_json(f"{INPUT_DIR}/annotations/test.json", f"{INPUT_DIR}/Images/test")

print(f"Train samples: {len(train_df)}")

from deep_translator import GoogleTranslator
import time

class VietnameseTranslator:
    """
    Module dịch thuật hai chiều Việt-Anh (nhất quán với B1).

    Chiến lược:
        Input (VI) → [GoogleTranslator vi→en] → BLIP-2 → Answer (EN)
                                                              ↓
                                           [GoogleTranslator en→vi] → Output (VI)
    """
    def __init__(self):
        self.vi_to_en = GoogleTranslator(source='vi', target='en')
        self.en_to_vi = GoogleTranslator(source='en', target='vi')
        self._cache_vi2en = {}
        self._cache_en2vi = {}

    def translate_question(self, text_vi: str) -> str:
        """Dịch câu hỏi: Tiếng Việt → Tiếng Anh"""
        if text_vi in self._cache_vi2en:
            return self._cache_vi2en[text_vi]
        try:
            result = self.vi_to_en.translate(text_vi)
            self._cache_vi2en[text_vi] = result
            return result
        except Exception as e:
            print(f"  Lỗi dịch Vi→En: {e}. Dùng nguyên bản.")
            return text_vi

    def translate_answer(self, text_en: str) -> str:
        """Dịch câu trả lời: Tiếng Anh → Tiếng Việt"""
        if text_en in self._cache_en2vi:
            return self._cache_en2vi[text_en]
        try:
            result = self.en_to_vi.translate(text_en)
            self._cache_en2vi[text_en] = result
            return result
        except Exception as e:
            print(f" Lỗi dịch En→Vi: {e}. Dùng nguyên bản.")
            return text_en

translator = VietnameseTranslator()

# ── Kiểm tra module dịch ─────────────────────────────────────────────────────
test_questions = [
    "Đây là món ăn gì?",
    "Màu sắc của món ăn này là gì?",
    "Có bao nhiêu miếng thịt trong bát?",
]
print("🔤 Kiểm tra module dịch thuật:")
print("-" * 55)
for q_vi in test_questions:
    q_en = translator.translate_question(q_vi)
    print(f"  VI: {q_vi}")
    print(f"  EN: {q_en}")
    print()

from tqdm.auto import tqdm
tqdm.pandas(desc="Đang dịch...")

# Dịch câu hỏi và câu trả lời sang cột mới
train_df['question_en'] = train_df['question'].progress_apply(translator.translate_question)
train_df['answer_en']   = train_df['answer'].progress_apply(translator.translate_answer)

val_df['question_en'] = val_df['question'].progress_apply(translator.translate_question)
val_df['answer_en']   = val_df['answer'].progress_apply(translator.translate_answer)

# Lưu lại để các lần chạy sau không phải dịch nữa!
train_df.to_csv(f"{WORKING_DIR}/train_translated.csv", index=False)
val_df.to_csv(f"{WORKING_DIR}/val_translated.csv", index=False)

print(" Đã dịch và lưu xong dữ liệu!")



import os
# VÁ LỖI KAGGLE: Ép hệ thống trỏ thẳng vào thư mục chứa thư viện CUDA
os.environ["LD_LIBRARY_PATH"] = "/usr/local/cuda/lib64:" + os.environ.get("LD_LIBRARY_PATH", "")

import torch
from transformers import BlipImageProcessor, AutoTokenizer, Blip2Processor, Blip2ForConditionalGeneration, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training

MODEL_NAME = "Salesforce/blip2-opt-2.7b"

# ── 1. Cấu hình Quantization 8-bit ──────────────────────────────────────────
quantization_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False
)

print(f"📥 Đang tải processor và mô hình gốc: {MODEL_NAME} ...")

# 1. Tải riêng Image Processor và Tokenizer
image_processor = BlipImageProcessor.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)

# 2. Ghép lại thành Blip2Processor
processor = Blip2Processor(image_processor=image_processor, tokenizer=tokenizer)

# 3. THÊM DÒNG NÀY ĐỂ FIX LỖI NONETYPE:
processor.num_query_tokens = 32

# Tải mô hình với cấu hình tự động phân bổ trên 2 GPU T4
base_model = Blip2ForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

print(" Đã tải xong mô hình gốc BLIP-2 (8-bit).")

# ── 2. Chuẩn bị model cho k-bit training ─────────────────────────────────────
base_model = prepare_model_for_kbit_training(base_model)

# ── 3. Cấu hình LoRA ─────────────────────────────────────────────────────────
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

# ── 4. Áp dụng LoRA vào model ────────────────────────────────────────────────
blip2_lora = get_peft_model(base_model, lora_config)

print("\n Kiểm tra tham số PEFT:")
blip2_lora.print_trainable_parameters()

# ── 5. Thống kê tham số chi tiết ─────────────────────────────────────────────
total_params     = sum(p.numel() for p in blip2_lora.parameters())
trainable_params = sum(p.numel() for p in blip2_lora.parameters() if p.requires_grad)

print("\n" + "=" * 55)
print("   THỐNG KÊ THAM SỐ MÔ HÌNH (LoRA)")
print("=" * 55)
print(f"   Tổng tham số       : {total_params / 1e6:.2f}M")
print(f"   Tham số trainable  : {trainable_params / 1e6:.4f}M")
print(f"   Tỉ lệ trainable    : {100 * trainable_params / total_params:.4f}%")
print("=" * 55)

from torch.utils.data import Dataset, DataLoader
from PIL import Image
import os


class VQAMonAnDataset(Dataset):
    def __init__(self, dataframe, processor, max_length=64):
        self.df          = dataframe.reset_index(drop=True)
        self.processor   = processor
        self.max_length  = max_length

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = row['image_path']

        try:
            image = Image.open(img_path).convert('RGB')
        except Exception as e:
            image = Image.new('RGB', (224, 224), (180, 180, 180))

        # Lấy trực tiếp câu tiếng Anh đã dịch sẵn
        question_en = str(row['question_en'])
        answer_en   = str(row['answer_en'])

        prompt = f"Question: {question_en}\nAnswer: {answer_en}"

        # ── Encode ────────────────────────────────────────────────────────────
        encoding = self.processor(
            images=image,
            text=prompt,
            return_tensors="pt",
            padding="max_length",
            max_length=self.max_length,
            truncation=True,
        )

        pixel_values = encoding['pixel_values'].squeeze(0)
        input_ids    = encoding['input_ids'].squeeze(0)

        # ── Tạo labels để tính loss ──────────────────────────────────────────
        labels = input_ids.clone()
        answer_token = self.processor.tokenizer.encode("Answer:", add_special_tokens=False)
        answer_pos = -1

        for i in range(len(input_ids) - len(answer_token)):
            if input_ids[i: i + len(answer_token)].tolist() == answer_token:
                answer_pos = i + len(answer_token)
                break

        if answer_pos > 0:
            labels[:answer_pos] = -100  # Mask phần prompt + câu hỏi

        # Mask padding tokens
        labels[labels == self.processor.tokenizer.pad_token_id] = -100

        return {
            'pixel_values': pixel_values,
            'input_ids':    input_ids,
            'labels':       labels,
        }


# ── Khởi tạo Dataset & DataLoader ────────────────────────────────────────────
print(" Đang xây dựng Train/Val Dataset (có dịch Vi→En)...")
print("   (Quá trình này cần gọi API Google Translate, có thể mất vài phút)")

train_df = pd.read_csv(f"{WORKING_DIR}/train_translated.csv")
val_df = pd.read_csv(f"{WORKING_DIR}/val_translated.csv")
# Đã bỏ biến IMG_DIR khi khởi tạo
train_dataset = VQAMonAnDataset(train_df, processor, max_length=64)
val_dataset = VQAMonAnDataset(val_df, processor, max_length=64)

# Cấu hình phần cứng
NUM_WORKERS = 4
BATCH_SIZE = 16 * num_gpus # 16 * 2 GPU = 32 images/batch

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print(f"\n Cấu hình DataLoader: Batch Size = {BATCH_SIZE} | Workers = {NUM_WORKERS}")
print(f" Train : {len(train_dataset)} mẫu | {len(train_loader)} batch")
print(f" Val   : {len(val_dataset)} mẫu | {len(val_loader)} batch")


from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
import math
from torch.cuda.amp import autocast
# ── Siêu tham số ─────────────────────────────────────────────────────────────
NUM_EPOCHS    = 3     # Bạn có thể tăng lên tuỳ ý
LR            = 1e-4
WARMUP_RATIO  = 0.1
GRAD_ACCUM    = 1     # Đã tăng BATCH_SIZE=16 nên không cần Accumulation quá lớn
MAX_GRAD_NORM = 1.0
SAVE_EVERY    = 1

total_steps   = (len(train_loader) // GRAD_ACCUM) * NUM_EPOCHS
warmup_steps  = int(total_steps * WARMUP_RATIO)

optimizer = AdamW(
    [p for p in blip2_lora.parameters() if p.requires_grad],
    lr=LR,
    weight_decay=0.01,
)
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps,
)

print(" Cấu hình Fine-tuning:")
print(f"   Số epoch          : {NUM_EPOCHS}")
print(f"   Learning rate     : {LR}")
print(f"   Batch size hiệu   : {4 * GRAD_ACCUM}")
print(f"   Total steps       : {total_steps}")
print(f"   Warmup steps      : {warmup_steps}")
print(f"   LoRA rank         : 16 | alpha: 32")


def train_epoch(model, loader, optimizer, scheduler, epoch, grad_accum=4):
    """Huấn luyện 1 epoch, trả về train loss."""
    model.train()
    total_loss  = 0.0
    num_batches = 0
    optimizer.zero_grad()

    progress = tqdm(loader, desc=f"Epoch {epoch} [Train]", leave=False)
    for step, batch in enumerate(progress):
        pixel_values = batch['pixel_values'].to(device, torch.float16)
        input_ids    = batch['input_ids'].to(device)
        labels       = batch['labels'].to(device)

        outputs = model(
            pixel_values=pixel_values,
            input_ids=input_ids,
            labels=labels,
        )
        loss = outputs.loss / grad_accum
        loss.backward()

        total_loss  += outputs.loss.item()
        num_batches += 1

        if (step + 1) % grad_accum == 0:
            torch.nn.utils.clip_grad_norm_(
                [p for p in model.parameters() if p.requires_grad],
                MAX_GRAD_NORM
            )
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()

        progress.set_postfix({'loss': f'{total_loss / num_batches:.4f}'})

    return total_loss / num_batches if num_batches > 0 else float('inf')


def validate_epoch(model, loader, epoch):
    """Đánh giá loss trên tập val."""
    model.eval()
    total_loss  = 0.0
    num_batches = 0

    with torch.no_grad():
        progress = tqdm(loader, desc=f"Epoch {epoch} [Val]", leave=False)
        for batch in progress:
            pixel_values = batch['pixel_values'].to(device, dtype=torch.float16)
            input_ids    = batch['input_ids'].to(device)
            labels       = batch['labels'].to(device)

            outputs = model(
                pixel_values=pixel_values,
                input_ids=input_ids,
                labels=labels,
            )
            total_loss  += outputs.loss.item()
            num_batches += 1
            progress.set_postfix({'val_loss': f'{total_loss / num_batches:.4f}'})

    return total_loss / num_batches if num_batches > 0 else float('inf')


# ── Vòng lặp huấn luyện chính ────────────────────────────────────────────────
print("\n" + "=" * 60)
blip2_lora.config.use_cache = False
print(" BẮT ĐẦU FINE-TUNING BLIP-2 + LoRA")
print("=" * 60)

train_losses = []
val_losses   = []
best_val_loss = float('inf')

for epoch in range(1, NUM_EPOCHS + 1):
    print(f"\n{'─' * 60}")
    print(f"  EPOCH {epoch}/{NUM_EPOCHS}")
    print(f"{'─' * 60}")

    train_loss = train_epoch(blip2_lora, train_loader, optimizer, scheduler, epoch, GRAD_ACCUM)
    val_loss   = validate_epoch(blip2_lora, val_loader, epoch)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    print(f"  Train Loss : {train_loss:.4f}  |  Val Loss : {val_loss:.4f}")

    # ── Lưu checkpoint ───────────────────────────────────────────────────────
    if epoch % SAVE_EVERY == 0:
        ckpt_path = os.path.join(CKPT_DIR, f'lora_adapter_epoch{epoch}')
        blip2_lora.save_pretrained(ckpt_path) # PEFT tự động quản lý lưu Multi-GPU an toàn
        print(f"  💾 Đã lưu LoRA adapter: {ckpt_path}")

    # ── Lưu model tốt nhất ───────────────────────────────────────────────────
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_ckpt_path = os.path.join(CKPT_DIR, 'lora_adapter_best')
        blip2_lora.save_pretrained(best_ckpt_path)
        print(f"  ⭐ Best model! Val Loss={val_loss:.4f} → lưu vào: {best_ckpt_path}")

print("\n" + "=" * 60)
print(" FINE-TUNING HOÀN TẤT!")
print(f"   Best Val Loss: {best_val_loss:.4f}")
print("=" * 60)


# ── Vẽ đường cong Loss ───────────────────────────────────────────────────────
epochs_range = list(range(1, NUM_EPOCHS + 1))

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(epochs_range, train_losses, 'o-', color='#E74C3C', label='Train Loss', linewidth=2)
ax.plot(epochs_range, val_losses,   's--', color='#3498DB', label='Val Loss',   linewidth=2)
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Loss', fontsize=12)
ax.set_title('B2 Fine-tuned (LoRA) — Learning Curves', fontsize=13)
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
ax.set_xticks(epochs_range)

# Annotate best epoch
best_epoch = val_losses.index(min(val_losses)) + 1
ax.axvline(x=best_epoch, color='#2ECC71', linestyle=':', linewidth=1.5,
           label=f'Best Epoch ({best_epoch})')
ax.legend(fontsize=10)

plt.tight_layout()
loss_curve_path = os.path.join(RESULTS_DIR, 'loss_curve_B2.png')
plt.savefig(loss_curve_path, dpi=150, bbox_inches='tight')
plt.show()
print(f" Đã lưu loss curve: {loss_curve_path}")


from peft import PeftModel

print(" Tải lại best LoRA adapter để đánh giá...")

# Tải lại base model
base_model_eval = Blip2ForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    quantization_config=BitsAndBytesConfig(load_in_8bit=True),
    device_map="auto",
    torch_dtype=torch.float16,
)

# Load LoRA adapter từ best checkpoint
blip2_eval = PeftModel.from_pretrained(base_model_eval, best_ckpt_path)
blip2_eval.eval()

print(f" Đã tải xong: {best_ckpt_path}")
print("   Sẵn sàng đánh giá trên tập Test.")

def infer_blip2_finetuned(
    image_pil: Image.Image,
    question_vi: str,
    return_english: bool = False,
    max_new_tokens: int = 30,
) -> str:
    """
    Inference với BLIP-2 đã fine-tune (nhất quán với infer_blip2_zeroshot trong B1).

    Pipeline:
        câu hỏi (VI) ──► dịch (VI→EN) ──► BLIP-2 (fine-tuned) ──► câu trả lời (EN)
                                                                            ↓
                                                        dịch (EN→VI) ──► câu trả lời (VI)

    Args:
        image_pil      : ảnh PIL RGB
        question_vi    : câu hỏi tiếng Việt
        return_english : nếu True, trả về tuple (vi, en)
        max_new_tokens : số token tối đa sinh ra

    Returns:
        Câu trả lời tiếng Việt (hoặc tuple nếu return_english=True)
    """
    # Bước 1: Dịch câu hỏi Vi → En
    question_en = translator.translate_question(question_vi)

    # Bước 2: Chuẩn bị input cho BLIP-2
    prompt = f"Question: {question_en}\nAnswer:"
    inputs = processor(
        images=image_pil,
        text=prompt,
        return_tensors="pt"
    ).to(device, torch.float16)

    # Bước 3: Sinh câu trả lời (model đã được fine-tune)
    with torch.no_grad():
        generated_ids = blip2_eval.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            num_beams=5,
            length_penalty=1.0,
            repetition_penalty=1.5,
            early_stopping=True,
        )

    # Bước 4: Giải mã output
    answer_en = processor.batch_decode(
        generated_ids, skip_special_tokens=True
    )[0].strip()

    if "Answer:" in answer_en:
        answer_en = answer_en.split("Answer:")[-1].strip()

    # Bước 5: Dịch câu trả lời En → Vi
    answer_vi = translator.translate_answer(answer_en)

    if return_english:
        return answer_vi, answer_en
    return answer_vi


# ── Kiểm tra nhanh với 3 mẫu từ tập test ────────────────────────────────────
print(" Kiểm tra inference fine-tuned với 3 mẫu ngẫu nhiên từ tập test:\n")
sample_rows = test_df.sample(3, random_state=99)  # Same random state as B1

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
for ax, (_, row) in zip(axes, sample_rows.iterrows()):
    img_name = row['image_path'].split('images/')[-1] \
               if 'images/' in str(row['image_path']) \
               else row['image_path']
    img_path = os.path.join(IMG_DIR, img_name)
    try:
        img = Image.open(img_path).convert('RGB')
    except Exception:
        img = Image.new('RGB', (224, 224), (200, 200, 200))

    answer_vi, answer_en = infer_blip2_finetuned(
        img, row['question'], return_english=True
    )

    ax.imshow(img)
    ax.axis('off')
    ax.set_title(
        f" {row['question']}\n"
        f" GT  : {row['answer']}\n"
        f" B2  : {answer_vi}\n"
        f"   (EN): {answer_en}",
        fontsize=8, loc='left', wrap=True
    )

plt.suptitle("B2 Fine-tuned — BLIP-2 + LoRA (Salesforce/blip2-opt-2.7b)",
             fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig(os.path.join(RESULTS_DIR, 'sample_predictions_B2.png'),
            bbox_inches='tight', dpi=150)
plt.show()
print("\n Inference fine-tuned hoạt động bình thường!")

import nltk
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from bert_score import score as bert_score_fn

nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)


def evaluate_b2_finetuned(test_df, img_dir, save_dir, max_new_tokens=20):

    predictions_vi = []
    predictions_en = []
    references_vi  = []
    questions_vi   = []
    image_names    = []

    print(" Đang chạy inference fine-tuned trên tập Test...")
    print(f"   Số mẫu: {len(test_df)} | Model: BLIP-2 + LoRA (fine-tuned)")
    print("-" * 55)

    for idx, row in tqdm(test_df.iterrows(), total=len(test_df), desc="B2 Inference"):
        img_name = row['image_path'].split('images/')[-1] \
                   if 'images/' in str(row['image_path']) \
                   else row['image_path']
        img_path = os.path.join(img_dir, img_name)

        try:
            img = Image.open(img_path).convert('RGB')
        except Exception:
            img = Image.new('RGB', (224, 224), (200, 200, 200))

        question_vi = str(row['question'])
        reference   = str(row['answer'])

        pred_vi, pred_en = infer_blip2_finetuned(
            img, question_vi,
            return_english=True,
            max_new_tokens=max_new_tokens
        )

        predictions_vi.append(pred_vi if pred_vi else "")
        predictions_en.append(pred_en if pred_en else "")
        references_vi.append(reference)
        questions_vi.append(question_vi)
        image_names.append(img_name)

    # ── Lưu predictions ──────────────────────────────────────────────────────
    results_df = pd.DataFrame({
        'image':          image_names,
        'question_vi':    questions_vi,
        'reference_vi':   references_vi,
        'prediction_vi':  predictions_vi,
        'prediction_en':  predictions_en,
    })
    results_csv_path = os.path.join(save_dir, 'predictions_B2.csv')
    results_df.to_csv(results_csv_path, index=False, encoding='utf-8-sig')
    print(f"\n💾 Đã lưu predictions: {results_csv_path}")

    # ── Tính các metric (nhất quán với B1) ───────────────────────────────────
    print("\n" + "=" * 55)
    print("   KẾT QUẢ ĐÁNH GIÁ B2 — FINE-TUNED (BLIP-2 + LoRA)")
    print("=" * 55)

    chencherry  = SmoothingFunction()
    nltk_preds  = [p.split() for p in predictions_vi]
    nltk_refs   = [[r.split()] for r in references_vi]

    bleu1 = corpus_bleu(nltk_refs, nltk_preds,
                        weights=(1,0,0,0),
                        smoothing_function=chencherry.method1)
    bleu4 = corpus_bleu(nltk_refs, nltk_preds,
                        weights=(0.25,0.25,0.25,0.25),
                        smoothing_function=chencherry.method1)
    print(f"1. BLEU-1 Score  : {bleu1 * 100:.2f} / 100")
    print(f"2. BLEU-4 Score  : {bleu4 * 100:.2f} / 100")

    rouge = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)
    rl_scores = [rouge.score(ref, pred)['rougeL'].fmeasure
                 for pred, ref in zip(predictions_vi, references_vi)]
    avg_rl = sum(rl_scores) / len(rl_scores) if rl_scores else 0
    print(f"3. ROUGE-L F1    : {avg_rl * 100:.2f} / 100")

    meteor_scores_list = [meteor_score([ref.split()], pred.split())
                          for pred, ref in zip(predictions_vi, references_vi)]
    avg_meteor = sum(meteor_scores_list) / len(meteor_scores_list) if meteor_scores_list else 0
    print(f"4. METEOR Score  : {avg_meteor * 100:.2f} / 100")

    def normalize(s):
        return str(s).lower().strip()

    exact_match = sum(
        normalize(p) == normalize(r)
        for p, r in zip(predictions_vi, references_vi)
    ) / len(references_vi)
    print(f"5. VQA Accuracy  : {exact_match * 100:.2f} / 100  (exact match)")

    print("\nĐang tính BERTScore (mbert)...")
    P, R, F1 = bert_score_fn(
        predictions_vi, references_vi,
        lang="vi",
        model_type="bert-base-multilingual-cased",
        verbose=False
    )
    avg_bert_f1 = F1.mean().item()
    print(f"6. BERTScore F1  : {avg_bert_f1 * 100:.2f} / 100")
    print("=" * 55)

    metrics = {
        'model':        'B2 Fine-tuned (BLIP-2 + LoRA)',
        'bleu1':        round(bleu1 * 100, 2),
        'bleu4':        round(bleu4 * 100, 2),
        'rougeL':       round(avg_rl * 100, 2),
        'meteor':       round(avg_meteor * 100, 2),
        'vqa_accuracy': round(exact_match * 100, 2),
        'bertscore_f1': round(avg_bert_f1 * 100, 2),
    }

    metrics_path = os.path.join(save_dir, 'metrics_B2.csv')
    pd.DataFrame([metrics]).to_csv(metrics_path, index=False)
    print(f"\n💾 Đã lưu metrics: {metrics_path}")

    return metrics, results_df


# ── Chạy đánh giá ────────────────────────────────────────────────────────────
b2_metrics, b2_results = evaluate_b2_finetuned(
    test_df, IMG_DIR, RESULTS_DIR
)

import numpy as np

metric_names  = ['BLEU-1', 'BLEU-4', 'ROUGE-L', 'METEOR', 'VQA Acc.', 'BERTScore']
metric_values = [
    b2_metrics['bleu1'],
    b2_metrics['bleu4'],
    b2_metrics['rougeL'],
    b2_metrics['meteor'],
    b2_metrics['vqa_accuracy'],
    b2_metrics['bertscore_f1'],
]

colors = ['#E74C3C', '#C0392B', '#E67E22', '#F39C12', '#2ECC71', '#27AE60']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Bar chart
bars = axes[0].bar(metric_names, metric_values, color=colors, edgecolor='black', linewidth=0.8)
axes[0].set_ylim(0, 100)
axes[0].set_ylabel('Score (%)', fontsize=12)
axes[0].set_title('B2 Fine-tuned — Điểm các Metric Đánh giá', fontsize=13, pad=12)
axes[0].tick_params(axis='x', rotation=15)
for bar, val in zip(bars, metric_values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                 f'{val:.1f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
axes[0].grid(axis='y', alpha=0.3)

# Radar chart
N = len(metric_names)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]
vals = metric_values + [metric_values[0]]

ax_radar = plt.subplot(122, polar=True)
ax_radar.plot(angles, vals, 'o-', linewidth=2, color='#E74C3C')
ax_radar.fill(angles, vals, alpha=0.25, color='#E74C3C')
ax_radar.set_xticks(angles[:-1])
ax_radar.set_xticklabels(metric_names, fontsize=9)
ax_radar.set_ylim(0, 100)
ax_radar.set_title('B2 Fine-tuned — Biểu đồ Radar', fontsize=13, pad=20)
ax_radar.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(RESULTS_DIR, 'metrics_chart_B2.png'), dpi=150, bbox_inches='tight')
plt.show()
print(" Đã lưu biểu đồ metric B2.")


def normalize(s):
    return str(s).lower().strip()

b2_results['correct'] = b2_results.apply(
    lambda r: normalize(r['prediction_vi']) == normalize(r['reference_vi']), axis=1
)

# ── Phân loại câu hỏi (nhất quán với B1) ────────────────────────────────────
def classify_question(q):
    q_lower = q.lower()
    if any(kw in q_lower for kw in ['có', 'không', 'phải', 'có phải']):
        return 'Yes/No'
    elif any(kw in q_lower for kw in ['bao nhiêu', 'mấy', 'số lượng']):
        return 'Đếm số'
    elif any(kw in q_lower for kw in ['màu', 'màu sắc']):
        return 'Màu sắc'
    elif any(kw in q_lower for kw in ['gì', 'là gì', 'đây là']):
        return 'Nhận dạng'
    elif any(kw in q_lower for kw in ['ở đâu', 'vị trí', 'bên']):
        return 'Không gian'
    else:
        return 'Khác'

b2_results['q_type'] = b2_results['question_vi'].apply(classify_question)

type_stats = b2_results.groupby('q_type').agg(
    total=('correct', 'count'),
    correct=('correct', 'sum')
).assign(accuracy=lambda x: x['correct'] / x['total'] * 100).sort_values('accuracy', ascending=False)

print(" Accuracy theo loại câu hỏi (B2 Fine-tuned):")
print("-" * 45)
print(f"{'Loại câu hỏi':<15} {'Tổng':>8} {'Đúng':>8} {'Accuracy':>12}")
print("-" * 45)
for q_type, row in type_stats.iterrows():
    print(f"{q_type:<15} {int(row['total']):>8} {int(row['correct']):>8} {row['accuracy']:>11.1f}%")
print("-" * 45)

# Biểu đồ
fig, ax = plt.subplots(figsize=(8, 4))
colors_type = ['#2ECC71' if v >= 50 else '#E74C3C' for v in type_stats['accuracy']]
ax.barh(type_stats.index, type_stats['accuracy'], color=colors_type, edgecolor='black', linewidth=0.5)
ax.set_xlabel('Accuracy (%)', fontsize=11)
ax.set_title('B2 Fine-tuned: Accuracy theo Loại câu hỏi', fontsize=13)
ax.axvline(x=50, color='gray', linestyle='--', alpha=0.6, label='50%')
for i, (idx, row) in enumerate(type_stats.iterrows()):
    ax.text(row['accuracy'] + 0.5, i, f"{row['accuracy']:.1f}%", va='center', fontsize=9)
ax.set_xlim(0, 110)
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(RESULTS_DIR, 'accuracy_by_qtype_B2.png'), dpi=150, bbox_inches='tight')
plt.show()

# ── Hiển thị ví dụ đúng/sai ──────────────────────────────────────────────────
correct_samples   = b2_results[b2_results['correct']].head(3)
incorrect_samples = b2_results[~b2_results['correct']].head(3)

def plot_samples(rows, title, color):
    fig, axes = plt.subplots(1, min(3, len(rows)), figsize=(5 * min(3, len(rows)), 5))
    if len(rows) == 1:
        axes = [axes]
    for ax, (_, row) in zip(axes, rows.iterrows()):
        img_name = row['image'].split('images/')[-1] \
                   if 'images/' in str(row['image']) \
                   else row['image']
        try:
            img = Image.open(os.path.join(IMG_DIR, img_name)).convert('RGB')
        except Exception:
            img = Image.new('RGB', (224, 224), (200, 200, 200))
        ax.imshow(img)
        ax.axis('off')
        ax.set_title(
            f" {row['question_vi']}\n"
            f" GT : {row['reference_vi']}\n"
            f" B2 : {row['prediction_vi']}",
            fontsize=8, loc='left', color=color
        )
    plt.suptitle(title, fontsize=13, color=color)
    plt.tight_layout()
    plt.show()

if len(correct_samples) > 0:
    plot_samples(correct_samples, " Dự đoán ĐÚNG (B2 Fine-tuned)", "green")
if len(incorrect_samples) > 0:
    plot_samples(incorrect_samples, " Dự đoán SAI (B2 Fine-tuned)", "red")

# ── Đọc kết quả B1 để so sánh ───────────────────────────────────────────────
b1_metrics_path = os.path.join(BASE_DIR, 'results_B1', 'metrics_B1.csv')
try:
    b1_df = pd.read_csv(b1_metrics_path)
    b1_row = b1_df.iloc[0]
    b1_bleu1 = b1_row['bleu1']
    b1_bleu4 = b1_row['bleu4']
    b1_rougeL = b1_row['rougeL']
    b1_meteor = b1_row['meteor']
    b1_vqa_acc = b1_row['vqa_accuracy']
    b1_bertscore = b1_row['bertscore_f1']
    print(" Đã đọc metrics B1.")
except Exception:
    # Placeholder nếu chưa có file B1
    b1_bleu1 = b1_bleu4 = b1_rougeL = b1_meteor = b1_vqa_acc = b1_bertscore = '—'
    print("  Không tìm thấy metrics_B1.csv — điền thủ công vào bảng.")

# ── Bảng so sánh tổng hợp ────────────────────────────────────────────────────
comparison_data = {
    'Cấu hình': [
        'A1 (LSTM Dec.)',
        'A2 (Transformer Dec.)',
        'B1 (Zero-shot)',
        'B2 (Fine-tuned LoRA)',
    ],
    'Mô tả': [
        'ViT + PhoBERT + LSTM Decoder',
        'ViT + PhoBERT + Transformer Decoder',
        'BLIP-2 opt-2.7b (zero-shot, Vi↔En)',
        'BLIP-2 opt-2.7b + LoRA r=16 (fine-tuned)',
    ],
    'BLEU-1':       ['—', '—', b1_bleu1,              b2_metrics['bleu1']],
    'BLEU-4':       ['—', '—', b1_bleu4,              b2_metrics['bleu4']],
    'ROUGE-L':      ['—', '—', b1_rougeL,             b2_metrics['rougeL']],
    'METEOR':       ['—', '—', b1_meteor,             b2_metrics['meteor']],
    'VQA Accuracy': ['—', '—', b1_vqa_acc,            b2_metrics['vqa_accuracy']],
    'BERTScore F1': ['—', '—', b1_bertscore,          b2_metrics['bertscore_f1']],
}

comparison_df = pd.DataFrame(comparison_data)
print("\n Bảng so sánh tổng hợp A1 / A2 / B1 / B2:")
print("   (Điền kết quả A1, A2 vào sau khi chạy notebook tương ứng)")
display(comparison_df)

comparison_df.to_csv(
    os.path.join(RESULTS_DIR, 'comparison_table_all_models.csv'),
    index=False, encoding='utf-8-sig'
)
print("\n Đã lưu bảng so sánh.")


try:
    # Chỉ vẽ nếu có đủ dữ liệu B1
    b1_vals = [float(b1_bleu1), float(b1_bleu4), float(b1_rougeL),
               float(b1_meteor), float(b1_vqa_acc), float(b1_bertscore)]
    b2_vals = [b2_metrics['bleu1'], b2_metrics['bleu4'], b2_metrics['rougeL'],
               b2_metrics['meteor'], b2_metrics['vqa_accuracy'], b2_metrics['bertscore_f1']]

    x      = np.arange(len(metric_names))
    width  = 0.35

    fig, ax = plt.subplots(figsize=(12, 5))
    bars1 = ax.bar(x - width/2, b1_vals, width, label='B1 Zero-shot',
                   color='#4ECDC4', edgecolor='black', linewidth=0.7)
    bars2 = ax.bar(x + width/2, b2_vals, width, label='B2 Fine-tuned (LoRA)',
                   color='#E74C3C', edgecolor='black', linewidth=0.7)

    ax.set_ylabel('Score (%)', fontsize=12)
    ax.set_title('So sánh B1 (Zero-shot) vs B2 (Fine-tuned LoRA)', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(metric_names, fontsize=10)
    ax.set_ylim(0, 110)
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)

    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=8)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=8)

    plt.tight_layout()
    compare_path = os.path.join(RESULTS_DIR, 'comparison_B1_vs_B2.png')
    plt.savefig(compare_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f" Đã lưu biểu đồ so sánh B1 vs B2: {compare_path}")

except (ValueError, TypeError):
    print("  Chưa có đủ dữ liệu B1 để so sánh. Chạy Notebook B1 trước.")


import io
from google.colab import files

def show_image(image_pil, title=""):
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.imshow(image_pil)
    if title:
        ax.set_title(title, fontsize=12, pad=8)
    ax.axis('off')
    plt.tight_layout()
    plt.show()


print("=" * 60)
print("     HỆ THỐNG HỎI-ĐÁP TRỰC QUAN (VQA) — MÔ HÌNH B2")
print("     BLIP-2 Fine-tuned (LoRA) + Dịch Việt↔Anh")
print("=" * 60)
print(" Lệnh đặc biệt:")
print("    - Nhập đường dẫn ảnh (ví dụ: /kaggle/input/.../001.jpg)")
print("    - random -> lấy ngẫu nhiên 1 ảnh từ Test set")
print("    - thoat  -> kết thúc chương trình")
print("=" * 60)

current_image = None
current_img_path = ""

while True:
    if current_image is None:
        user_input = input("\n Nhập đường dẫn ảnh hoặc 'random': ").strip()

        if user_input.lower() in ['thoat', 'exit', 'quit']:
            break

        if user_input.lower() == 'random':
            random_row = test_df.sample(1).iloc[0]
            current_img_path = os.path.join(IMG_DIR, random_row['image_path'])
        else:
            current_img_path = user_input

        try:
            current_image = Image.open(current_img_path).convert('RGB')
            show_image(current_image, title=f"📷 {os.path.basename(current_img_path)}")
        except Exception as e:
            print(f" Không thể đọc ảnh từ {current_img_path}: {e}")
            current_image = None
            continue

    question = input("\n Câu hỏi tiếng Việt (new = ảnh mới | thoat = thoát): ").strip()

    if question.lower() in ['thoat', 'exit', 'quit']:
        print("\n Đã dừng chương trình.")
        break

    if question.lower() == 'new':
        current_image = None
        print("-" * 60)
        continue

    if question == '':
        print("  Vui lòng nhập câu hỏi.")
        continue

    answer_vi, answer_en = infer_blip2_finetuned(
        current_image, question, return_english=True
    )
    q_en = translator.translate_question(question)

    print("-" * 60)
    print(f"   Câu hỏi (EN) : {q_en}")
    print(f"   Trả lời (EN) : {answer_en}")
    print(f"  🇻🇳 Trả lời (VI) : {answer_vi}")
    print("-" * 60)

