# -*- coding: utf-8 -*-
"""finetune_bartpho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi04ZZB4b3luy0MYAoqnk9uj9RW-1Dyt

# Fine-tuning BARTpho — Abstractive Text Summarization (Vietnamese)

**Model:** `vinai/bartpho-syllable`  
**Task:** Seq2Seq Summarization — document → summary  
**Data:** VnExpress news articles (6 categories, ~3000 samples)  
**Runtime:** Google Colab · GPU T4 16 GB  

---

| Hyperparameter | Value | Rationale |
|---|---|---|
| `learning_rate` | 3e-5 | Lewis et al. (2020) BART fine-tuning |
| `batch_size` (effective) | 32 | 4 × gradient_accumulation 8 |
| `max_input_length` | 1024 | Median doc ~825 syllable tokens |
| `max_target_length` | 128 | Median summary ~45 syllable tokens |
| `fp16` | True | T4 Tensor Cores, giảm ~40% VRAM |
| `label_smoothing` | 0.1 | Szegedy et al. (2016), dataset nhỏ |
| `num_beams` | 4 | Beam search inference |

## 0. Cài đặt thư viện
"""

!pip install -q -U transformers datasets evaluate rouge_score
!pip install -q sentencepiece accelerate

"""## 1. Import & Cấu hình"""

import json
import math
import logging
from dataclasses import dataclass
from typing import Optional

import numpy as np
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback,
    set_seed,
)
from datasets import Dataset, DatasetDict
import evaluate

logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S',
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)} | "
          f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print('WARNING: GPU not found.')

@dataclass
class Config:
    # Data
    data_path:   str   = 'dataset_vnexpress_3000_clean.json'
    train_ratio: float = 0.80
    val_ratio:   float = 0.10
    test_ratio:  float = 0.10
    seed:        int   = 42

    # Model
    # Dùng phiên bản syllable, bỏ qua bước word segmentation ngoài.
    model_name: str = 'vinai/bartpho-syllable'

    # Tokenization
    # Median doc ~825 syllable tokens, max BARTpho = 1024.
    # Giảm xuống 512 nếu OOM.
    max_input_length:  int = 1024
    max_target_length: int = 128

    # Training
    output_dir:                  str   = './bartpho_summarization'
    num_train_epochs:            int   = 10
    per_device_train_batch_size: int   = 4
    per_device_eval_batch_size:  int   = 4
    gradient_accumulation_steps: int   = 8
    learning_rate:               float = 3e-5
    weight_decay:                float = 0.01
    warmup_ratio:                float = 0.05
    fp16:                        bool  = True
    label_smoothing_factor:      float = 0.1

    # Generation
    num_beams:            int   = 4
    length_penalty:       float = 1.0
    no_repeat_ngram_size: int   = 3

    # Early stopping
    early_stopping_patience: int = 3
    eval_steps:    int = 100
    save_steps:    int = 100
    logging_steps: int = 50


cfg = Config()
set_seed(cfg.seed)
print(f'Config loaded. Model: {cfg.model_name} | Seed: {cfg.seed}')

"""## 2. Load & Phân chia Dataset

Phân chia theo thứ tự để tránh data leakage:
1. Tách **test (10%)** ra khỏi toàn bộ dataset trước.
2. Từ 90% còn lại, tách **val (10/90 ≈ 11.1%)** ra khỏi train.

Tập test chỉ được dùng **một lần duy nhất** để báo cáo kết quả cuối.
"""

def load_and_split_dataset(config: Config) -> DatasetDict:
    with open(config.data_path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    processed = [
        {'article': item['document'], 'summary': item['summary']}
        for item in raw_data
        if item.get('document') and item.get('summary')
    ]

    full_dataset = Dataset.from_list(processed)

    train_val = full_dataset.train_test_split(
        test_size=config.test_ratio, seed=config.seed
    )
    val_ratio_adjusted = config.val_ratio / (config.train_ratio + config.val_ratio)
    train_val_split = train_val['train'].train_test_split(
        test_size=val_ratio_adjusted, seed=config.seed
    )

    return DatasetDict({
        'train':      train_val_split['train'],
        'validation': train_val_split['test'],
        'test':       train_val['test'],
    })


raw_datasets = load_and_split_dataset(cfg)
total = sum(len(v) for v in raw_datasets.values())
for split, ds in raw_datasets.items():
    print(f'  {split:>12}: {len(ds):>5} samples ({len(ds)/total*100:.1f}%)')

"""## 3. Tokenization

- **Input:** truncate đến `max_input_length=1024`, padding=False (DataCollator xử lý dynamic padding).
- **Target:** dùng `text_target` để BARTpho áp dụng đúng special tokens cho decoder side.
- **Labels:** padding được thay bằng `-100` bởi DataCollator để không đóng góp vào loss.
"""

tokenizer = AutoTokenizer.from_pretrained(cfg.model_name, use_fast=True)


def build_preprocess_function(tokenizer, config: Config):
    def preprocess_function(examples: dict) -> dict:
        model_inputs = tokenizer(
            examples['article'],
            max_length=config.max_input_length,
            truncation=True,
            padding=False,
        )
        labels = tokenizer(
            text_target=examples['summary'],
            max_length=config.max_target_length,
            truncation=True,
            padding=False,
        )
        model_inputs['labels'] = labels['input_ids']
        return model_inputs
    return preprocess_function


preprocess_fn = build_preprocess_function(tokenizer, cfg)

tokenized_datasets = raw_datasets.map(
    preprocess_fn,
    batched=True,
    batch_size=64,
    remove_columns=['article', 'summary'],
    desc='Tokenizing',
)

sample_lengths = [len(x) for x in tokenized_datasets['train']['input_ids'][:200]]
n_truncated = sum(l >= cfg.max_input_length for l in sample_lengths)
print(f'Input token length (200 samples):')
print(f'  mean      : {np.mean(sample_lengths):.0f}')
print(f'  max       : {max(sample_lengths)}')
print(f'  truncated : {n_truncated}')

"""## 4. Evaluation — ROUGE Metrics

**ROUGE** (Lin, 2004) đo mức trùng lặp n-gram giữa hypothesis và reference.
Là tiêu chuẩn đánh giá summarization trong các benchmark CNN/DailyMail, XSum, ViNewsSum.

| Metric | Đo lường |
|---|---|
| ROUGE-1 | Overlap unigram — coverage từ vựng |
| ROUGE-2 | Overlap bigram — mạch lạc cục bộ |
| ROUGE-L | Longest Common Subsequence — cấu trúc câu |
| ROUGE-Lsum | ROUGE-L per sentence, phù hợp output nhiều câu |

> **Hạn chế:** ROUGE không đo semantic similarity.
"""

rouge_metric = evaluate.load('rouge')


def build_compute_metrics(tokenizer, config: Config):
    def compute_metrics(eval_preds) -> dict:
        predictions, labels = eval_preds

        if isinstance(predictions, tuple):
            predictions = predictions[0]

        # Cả predictions lẫn labels đều có thể chứa -100 (padding của Trainer).
        # BARTpho tokenizer không decode được -100 -> replace về pad_token_id trước.
        predictions = predictions.tolist() if hasattr(predictions, 'tolist') else predictions
        predictions = [
            [t if t != -100 else tokenizer.pad_token_id for t in pred]
            for pred in predictions
        ]

        labels = labels.tolist() if hasattr(labels, 'tolist') else labels
        labels = [
            [t if t != -100 else tokenizer.pad_token_id for t in label]
            for label in labels
        ]

        decoded_preds = tokenizer.batch_decode(
            predictions,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=True,
        )
        decoded_labels = tokenizer.batch_decode(
            labels,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=True,
        )

        decoded_preds  = [p.strip() for p in decoded_preds]
        decoded_labels = [l.strip() for l in decoded_labels]

        result = rouge_metric.compute(
            predictions=decoded_preds,
            references=decoded_labels,
            use_stemmer=False,
            use_aggregator=True,
        )
        result = {k: round(v * 100, 4) for k, v in result.items()}

        pred_lens = [
            sum(1 for t in pred if t != tokenizer.pad_token_id)
            for pred in predictions
        ]
        result['gen_len'] = round(sum(pred_lens) / len(pred_lens), 2)

        return result

    return compute_metrics


compute_metrics_fn = build_compute_metrics(tokenizer, cfg)
print('compute_metrics ready.')

"""## 5. Training Arguments

`Seq2SeqTrainingArguments` extends `TrainingArguments` với:
- `predict_with_generate=True`: chạy beam search khi evaluate, bắt buộc để ROUGE chính xác.
- `eval_strategy`: đổi từ `evaluation_strategy` trong transformers >= 4.41.
- `gradient_checkpointing=True`: tiết kiệm ~30% VRAM.
"""

steps_per_epoch = math.ceil(
    len(tokenized_datasets['train'])
    / (cfg.per_device_train_batch_size * cfg.gradient_accumulation_steps)
)
total_steps  = steps_per_epoch * cfg.num_train_epochs
warmup_steps = int(total_steps * cfg.warmup_ratio)

print(f'steps/epoch : {steps_per_epoch}')
print(f'total steps : {total_steps}')
print(f'warmup steps: {warmup_steps}')

training_args = Seq2SeqTrainingArguments(
    output_dir=cfg.output_dir,

    per_device_train_batch_size=cfg.per_device_train_batch_size,
    per_device_eval_batch_size=cfg.per_device_eval_batch_size,
    gradient_accumulation_steps=cfg.gradient_accumulation_steps,

    learning_rate=cfg.learning_rate,
    weight_decay=cfg.weight_decay,
    warmup_steps=warmup_steps,

    num_train_epochs=cfg.num_train_epochs,
    eval_strategy='steps',
    eval_steps=cfg.eval_steps,
    save_strategy='steps',
    save_steps=cfg.save_steps,
    logging_steps=cfg.logging_steps,

    fp16=cfg.fp16,
    label_smoothing_factor=cfg.label_smoothing_factor,

    predict_with_generate=True,
    generation_max_length=cfg.max_target_length,
    generation_num_beams=cfg.num_beams,

    load_best_model_at_end=True,
    metric_for_best_model='rouge1',
    greater_is_better=True,
    save_total_limit=2,

    gradient_checkpointing=True,
    dataloader_num_workers=2,

    seed=cfg.seed,
    report_to='none',
    push_to_hub=False,
)

print('TrainingArguments ready.')

"""## 6. Fine-tuning

Pipeline:
1. Load model từ HuggingFace Hub.
2. Khởi tạo `DataCollatorForSeq2Seq` — dynamic padding per batch.
3. Khởi tạo `Seq2SeqTrainer` với `EarlyStoppingCallback`.
4. `trainer.train()`.
5. Evaluate trên test set **một lần duy nhất** sau khi training xong.
"""

model = AutoModelForSeq2SeqLM.from_pretrained(cfg.model_name)

# Dùng generation_config thay vì model.config để tránh lỗi với transformers >= 4.41.
if tokenizer.bos_token_id is not None:
    model.generation_config.forced_bos_token_id = tokenizer.bos_token_id

total_p   = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Params: {total_p/1e6:.1f}M total | {trainable/1e6:.1f}M trainable')

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    label_pad_token_id=-100,
    pad_to_multiple_of=8 if cfg.fp16 else None,
)

# processing_class thay vì tokenizer trong Trainer từ transformers >= 4.41.
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics_fn,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=cfg.early_stopping_patience,
            early_stopping_threshold=0.01,
        )
    ],
)

print('Trainer ready.')

train_result = trainer.train()
trainer.log_metrics('train', train_result.metrics)
trainer.save_metrics('train', train_result.metrics)

# Chỉ chạy một lần sau khi training hoàn tất.
test_results = trainer.evaluate(
    eval_dataset=tokenized_datasets['test'],
    metric_key_prefix='test',
)
trainer.log_metrics('test', test_results)
trainer.save_metrics('test', test_results)

print('\nTest Results:')
for k, v in test_results.items():
    if 'rouge' in k.lower() or 'gen_len' in k.lower():
        print(f'  {k:<25}: {v:.4f}')

"""---
## 7. Trực quan hóa quá trình huấn luyện

Trích xuất log từ `trainer.state.log_history` và vẽ các biểu đồ:
- **Training Loss** theo steps
- **Validation Loss** theo steps
- **ROUGE-1 / ROUGE-2 / ROUGE-L** theo steps
- **Generated Length** trung bình theo steps
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from IPython.display import display

# trainer.state.log_history là list các dict, mỗi dict là một log entry.
# Entry training: có 'loss' và 'learning_rate'.
# Entry evaluation: có 'eval_loss', 'eval_rouge1', 'eval_rouge2', 'eval_rougeL', 'eval_gen_len'.
log_history = trainer.state.log_history

train_logs = [
    {'step': e['step'], 'train_loss': e['loss'], 'lr': e.get('learning_rate', None)}
    for e in log_history
    if 'loss' in e and 'eval_loss' not in e
]

eval_logs = [
    {
        'step':        e['step'],
        'eval_loss':   e.get('eval_loss'),
        'rouge1':      e.get('eval_rouge1'),
        'rouge2':      e.get('eval_rouge2'),
        'rougeL':      e.get('eval_rougeL'),
        'rougeLsum':   e.get('eval_rougeLsum'),
        'gen_len':     e.get('eval_gen_len'),
    }
    for e in log_history
    if 'eval_loss' in e
]

df_train = pd.DataFrame(train_logs)
df_eval  = pd.DataFrame(eval_logs)

print(f'Training log entries : {len(df_train)}')
print(f'Evaluation log entries: {len(df_eval)}')
print('\nEval columns:', df_eval.columns.tolist())
display(df_eval.tail())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Training & Validation Loss', fontsize=14, fontweight='bold', y=1.02)

# Training loss
ax = axes[0]
ax.plot(df_train['step'], df_train['train_loss'],
        color='#3182ce', linewidth=1.5, alpha=0.8, label='Train Loss')
# Smoothed line (rolling mean)
if len(df_train) > 10:
    smoothed = df_train['train_loss'].rolling(window=10, min_periods=1).mean()
    ax.plot(df_train['step'], smoothed,
            color='#1a56a0', linewidth=2.5, label='Train Loss (smoothed)')
ax.set_title('Training Loss')
ax.set_xlabel('Steps')
ax.set_ylabel('Loss')
ax.legend()
ax.grid(True, alpha=0.3)
ax.spines[['top', 'right']].set_visible(False)

# Validation loss
ax = axes[1]
ax.plot(df_eval['step'], df_eval['eval_loss'],
        color='#e53e3e', linewidth=2, marker='o', markersize=5, label='Val Loss')
# Mark best checkpoint
best_idx = df_eval['eval_loss'].idxmin()
ax.scatter(df_eval.loc[best_idx, 'step'], df_eval.loc[best_idx, 'eval_loss'],
           color='#276749', s=120, zorder=5, label=f'Best (step={df_eval.loc[best_idx, "step"]})')
ax.set_title('Validation Loss')
ax.set_xlabel('Steps')
ax.set_ylabel('Loss')
ax.legend()
ax.grid(True, alpha=0.3)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('loss_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: loss_curves.png')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('ROUGE Scores on Validation Set', fontsize=14, fontweight='bold', y=1.02)

rouge_colors = {
    'rouge1':    ('#3182ce', 'ROUGE-1'),
    'rouge2':    ('#e53e3e', 'ROUGE-2'),
    'rougeL':    ('#38a169', 'ROUGE-L'),
    'rougeLsum': ('#d69e2e', 'ROUGE-Lsum'),
}

# ROUGE-1 / ROUGE-2 / ROUGE-L trên cùng trục
ax = axes[0]
for key, (color, label) in rouge_colors.items():
    if key in df_eval.columns and df_eval[key].notna().any():
        ax.plot(df_eval['step'], df_eval[key],
                color=color, linewidth=2, marker='o', markersize=4, label=label)
ax.set_title('ROUGE Scores')
ax.set_xlabel('Steps')
ax.set_ylabel('Score (0 - 100)')
ax.legend()
ax.grid(True, alpha=0.3)
ax.spines[['top', 'right']].set_visible(False)

# Print best ROUGE-1 tại step tốt nhất
if 'rouge1' in df_eval.columns and df_eval['rouge1'].notna().any():
    best_r1_idx = df_eval['rouge1'].idxmax()
    ax.scatter(df_eval.loc[best_r1_idx, 'step'], df_eval.loc[best_r1_idx, 'rouge1'],
               color='#1a1a2e', s=120, zorder=5,
               label=f'Best ROUGE-1={df_eval.loc[best_r1_idx, "rouge1"]:.2f}')
    ax.legend()

# Generated length
ax = axes[1]
if 'gen_len' in df_eval.columns and df_eval['gen_len'].notna().any():
    ax.plot(df_eval['step'], df_eval['gen_len'],
            color='#805ad5', linewidth=2, marker='s', markersize=5, label='Avg Gen Length')
    ax.axhline(y=cfg.max_target_length, color='gray', linestyle='--',
               alpha=0.6, label=f'max_target_length={cfg.max_target_length}')
ax.set_title('Average Generated Length (tokens)')
ax.set_xlabel('Steps')
ax.set_ylabel('Tokens')
ax.legend()
ax.grid(True, alpha=0.3)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('rouge_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: rouge_curves.png')

fig, ax = plt.subplots(figsize=(10, 4))

if 'lr' in df_train.columns and df_train['lr'].notna().any():
    ax.plot(df_train['step'], df_train['lr'],
            color='#dd6b20', linewidth=2, label='Learning Rate')
    ax.set_title('Learning Rate Schedule (Warmup + Linear Decay)', fontsize=12)
    ax.set_xlabel('Steps')
    ax.set_ylabel('Learning Rate')
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.2e'))
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.spines[['top', 'right']].set_visible(False)

    plt.tight_layout()
    plt.savefig('lr_schedule.png', dpi=150, bbox_inches='tight')
    plt.show()
    print('Saved: lr_schedule.png')
else:
    print('Learning rate không có trong log. Tăng logging_steps hoặc kiểm tra log_history.')

from IPython.display import display, HTML

# Bảng tổng hợp kết quả tốt nhất
best_eval = df_eval.loc[df_eval['rouge1'].idxmax()] if 'rouge1' in df_eval.columns else df_eval.iloc[-1]

rows = ''
metrics_display = [
    ('ROUGE-1',         f"{best_eval.get('rouge1', 'N/A'):.4f}"    if best_eval.get('rouge1') else 'N/A'),
    ('ROUGE-2',         f"{best_eval.get('rouge2', 'N/A'):.4f}"    if best_eval.get('rouge2') else 'N/A'),
    ('ROUGE-L',         f"{best_eval.get('rougeL', 'N/A'):.4f}"    if best_eval.get('rougeL') else 'N/A'),
    ('ROUGE-Lsum',      f"{best_eval.get('rougeLsum', 'N/A'):.4f}" if best_eval.get('rougeLsum') else 'N/A'),
    ('Val Loss',        f"{best_eval.get('eval_loss', 'N/A'):.4f}"  if best_eval.get('eval_loss') else 'N/A'),
    ('Avg Gen Length',  f"{best_eval.get('gen_len', 'N/A'):.1f}"   if best_eval.get('gen_len') else 'N/A'),
    ('Best Step',       str(int(best_eval.get('step', 0)))),
]

for name, val in metrics_display:
    rows += (
        f'<tr>'
        f'<td style="padding:8px 16px;border-bottom:1px solid #e2e8f0;color:#4a5568;">{name}</td>'
        f'<td style="padding:8px 16px;border-bottom:1px solid #e2e8f0;font-weight:600;color:#1a202c;text-align:right;">{val}</td>'
        f'</tr>'
    )

html = (
    '<div style="font-family:Segoe UI,Arial,sans-serif;max-width:480px;margin:16px 0;'
    'border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">'
    '<div style="background:#1a1a2e;color:#fff;padding:12px 16px;font-weight:600;font-size:14px;">'
    'Best Validation Results</div>'
    f'<table style="width:100%;border-collapse:collapse;">{rows}</table>'
    '</div>'
)
display(HTML(html))

save_path = f'{cfg.output_dir}/final_model'
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)
print(f'Model saved: {save_path}')

"""---
## 8. Inference Demo
"""

def summarize(text: str, model_path: str, config: Config = None) -> dict:
    if config is None:
        config = Config()

    _device = 'cuda' if torch.cuda.is_available() else 'cpu'
    _tok    = AutoTokenizer.from_pretrained(model_path)
    _model  = AutoModelForSeq2SeqLM.from_pretrained(model_path).eval().to(_device)

    inputs = _tok(
        text,
        max_length=config.max_input_length,
        truncation=True,
        return_tensors='pt',
    ).to(_device)

    with torch.no_grad():
        output_ids = _model.generate(
            **inputs,
            max_new_tokens=config.max_target_length,
            num_beams=config.num_beams,
            length_penalty=config.length_penalty,
            no_repeat_ngram_size=config.no_repeat_ngram_size,
            early_stopping=True,
        )

    summary = _tok.decode(
        output_ids[0],
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True,
    )
    return {
        'summary':       summary.strip(),
        'input_tokens':  inputs['input_ids'].shape[1],
        'output_tokens': output_ids.shape[1],
    }


print('summarize() ready.')

from IPython.display import display, HTML


def render_result(domain: str, input_text: str, result: dict) -> None:
    compression = result['input_tokens'] / max(result['output_tokens'], 1)
    word_count  = len(input_text.split())
    preview     = input_text.strip()[:320].replace('<', '&lt;').replace('>', '&gt;')
    if len(input_text.strip()) > 320:
        preview += '...'
    summary_html = result['summary'].replace('<', '&lt;').replace('>', '&gt;')

    badge = (
        'background:#16213e;color:{color};'
        'padding:3px 10px;border-radius:20px;font-size:11px;'
    )
    html = (
        '<div style="font-family:Segoe UI,Arial,sans-serif;max-width:820px;'
        'margin:16px 0;border:1px solid #e0e0e0;border-radius:10px;'
        'overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.07);">'

        '<div style="background:#1a1a2e;color:#fff;padding:12px 20px;'
        'display:flex;justify-content:space-between;align-items:center;">'
        f'<span style="font-weight:600;font-size:14px;">BARTpho &mdash; {domain}</span>'
        '<div style="display:flex;gap:8px;">'
        f'<span style="{badge.format(color="#a0aec0")}">{word_count} words</span>'
        f'<span style="{badge.format(color="#a0aec0")}">{result["input_tokens"]} tokens in</span>'
        f'<span style="{badge.format(color="#68d391")}">{result["output_tokens"]} tokens out</span>'
        f'<span style="{badge.format(color="#f6ad55")}">{compression:.1f}x compression</span>'
        '</div></div>'

        '<div style="padding:16px 20px;background:#fafafa;border-bottom:1px solid #e0e0e0;">'
        '<div style="font-size:11px;font-weight:600;text-transform:uppercase;'
        'letter-spacing:0.8px;color:#718096;margin-bottom:8px;">Input Document</div>'
        f'<div style="font-size:13.5px;color:#4a5568;line-height:1.65;">{preview}</div>'
        '</div>'

        '<div style="padding:16px 20px;background:#fff;">'
        '<div style="font-size:11px;font-weight:600;text-transform:uppercase;'
        'letter-spacing:0.8px;color:#38a169;margin-bottom:8px;">Generated Summary</div>'
        '<div style="font-size:14.5px;color:#1a202c;line-height:1.7;font-weight:500;'
        'padding:12px 16px;background:#f0fff4;'
        f'border-left:4px solid #38a169;border-radius:0 6px 6px 0;">{summary_html}</div>'
        '</div></div>'
    )
    display(HTML(html))

MODEL_PATH = f'{cfg.output_dir}/final_model'

samples = [
    (
        'Cong nghe',
        'Apple vua ra mat dong iPhone 16 voi chip A18 Pro moi nhat. '
        'Chip A18 Pro duoc san xuat tren tien trinh 3nm the he hai, '
        'mang lai hieu nang CPU nhanh hon 15% va GPU nhanh hon 20% so voi the he truoc. '
        'iPhone 16 Pro ho tro Apple Intelligence, cho phep nguoi dung tom tat van ban '
        'va chinh sua anh bang AI. May co ba bien the mau moi, pin lon hon va camera '
        'nang cap voi kha nang quay video 4K 120fps. '
        'Gia khoi diem iPhone 16 la 799 USD, iPhone 16 Pro Max la 1.199 USD.',
    ),
    (
        'Suc khoe',
        'Cac nha khoa hoc tu Dai hoc Harvard cong bo nghien cuu cho thay ngu du '
        '7-9 tieng moi dem co the giam nguy co mac benh tim mach len den 30%. '
        'Nghien cuu theo doi hon 50.000 nguoi trong 10 nam, phat hien nhung nguoi '
        'ngu it hon 6 tieng hoac nhieu hon 9 tieng co nguy co cao hon mac benh '
        'tim mach, huyet ap va tieu duong type 2. '
        'Giao su Frank Hu khuyen cao tranh dung dien thoai truoc khi ngu.',
    ),
    (
        'Kinh doanh',
        'Ngan hang Nha nuoc Viet Nam vua dieu chinh ty gia trung tam USD/VND '
        'len muc 24.250 dong, tang 50 dong so voi phien truoc. '
        'Quyet dinh duoc dua ra trong boi canh dong USD tang manh tren thi truong '
        'quoc te sau khi Cuc Du tru Lien bang My phat tin hieu duy tri lai suat cao. '
        'Cac chuyen gia nhan dinh ty gia co the tiep tuc chiu ap luc trong quy III.',
    ),
]

for domain, text in samples:
    result = summarize(text, MODEL_PATH, cfg)
    render_result(domain, text, result)